### ISSUE TITLE
Code Execution can't be Processed

### ISSUE THREAD

**Issue by Prem160902** [ange-yaghi/engine-sim#101]
Upon double clicking & installing the **engine-sim-app.exe**, the system prompted an error saying "_The code execution cannot proceed because d3dx11_43.dll was not found. Reinstalling the program may fix this problem._"

![Screenshot 2022-08-15 184204](https://user-images.githubusercontent.com/108966597/184642008-5db21630-142c-4fda-9262-7d77302670d9.png)

**Comment by MrAmos123** [comment]
Install DirectX https://www.microsoft.com/en-gb/download/details.aspx?id=35
