### ISSUE TITLE
Changine engine MAIN.MR problem

### ISSUE THREAD

**Issue by Knifeisuk** [ange-yaghi/engine-sim#103]
So i would love to change the engine and follwing the instructions it tells me to go into main.mr to add a new import after the first **3** even though i have 2 this is the code in my main.mr
 

import "engine_sim.mr"
import "engines/kohler/kohler_ch750.mr"

set_engine(
    engine: kohler_ch750()
)

**Comment by l0wigh** [comment]
You just have to change the last import to put the one you want. And then change the ```engine:``` part.

**Comment by TWINKIEFROMH3LL** [comment]
even though this was posted bit ago, i'd like to add that you can just add import lines instead of changing the last, that way you can just change the set engine line and run whatever you want

**Comment by Jckf** [comment]
Problem seems to have been resolved. Closing.
