### ISSUE TITLE
Minor issue: Application window resizing/relocating issues

### ISSUE THREAD

**Issue by JaoLuca** [ange-yaghi/engine-sim#104]
While resizing the application window the font size of some dialog boxes does not adjust as well as the rest of the GUI does. The font size could change dynamically or it could disappear after hitting its wall. A minimum window size could be implemented as well to avoid more problems.

Also, while moving the window around, a 1 second long audio loop takes place instead of the audio simulation.

![2022-08-15](https://user-images.githubusercontent.com/93227544/184714361-3659f10f-bb8e-4892-b209-9f02b7614dc5.png)

**Comment by Jckf** [comment]
Related https://github.com/ange-yaghi/engine-sim/issues/94
