### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by XxK3V1NxX** [ange-yaghi/engine-sim#105]
El audio del programa se escucha trabado y se superpone.
No se si es por mi PC pero estoy tratado de averiguar el error, por favor necesito ayuda.

Gracias.

**Comment by Jckf** [comment]
Please read [the FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) for information about stuttering and/or repeating audio.
