### ISSUE TITLE
Ignition gets cut off if engine runs backwards

### ISSUE THREAD

**Issue by Kevin15673** [ange-yaghi/engine-sim#106]
I want to make engine that runs backwards, plz fix ty

**Comment by VenomousSteam81** [comment]
that is an amazing idea. implement or fix lol

**Comment by 14rss** [comment]
As in a reverse gear?

**Comment by Kevin15673** [comment]
> As in a reverse gear?

No, if the engine is rotating counterclockwise ignition gets shut off

**Comment by cmdrscotty** [comment]
> > As in a reverse gear?
> 
> No, if the engine is rotating counterclockwise ignition gets shut off

Would love to see that implemented. Functionality wise not sure if anything beyond the need for flipping the engine rendering so it shows it running backwards (there's already a value for flipping the render of the camshafts intake/exhaust sides)

**Comment by Kevin15673** [comment]
Why would anything rendering wise need to be changed? All you'd need to do
to get an engine running in reverse is flipping the camshafts and getting
the ignition timing right

**Comment by ange-yaghi** [comment]
I just made some changes that will allow engines to spin CCW without cutting ignition.
