### ISSUE TITLE
Build error on WSL

### ISSUE THREAD

**Issue by alegrevers** [ange-yaghi/engine-sim#107]
Hey guys, I had some trouble installing but it's solved. But now, the build broke every time and shows me this:

I'm getting a lot of error messages and it pass the character limits of this box, so I attached a file with the errors.

So, if you know this error, please tell me.

thx

[cmake error.txt](https://github.com/ange-yaghi/engine-sim/files/9347420/cmake.error.txt)

**Comment by Najsr** [comment]
AFAIK this simulator is Windows only at least for now.

**Comment by arghanath007** [comment]
Will it ever come to Linux? Any chance?

**Comment by bobsayshilol** [comment]
Check #2 or the discord for current Linux/Mac/Web porting progress
