### ISSUE TITLE
Unable to get engine into gear.

### ISSUE THREAD

**Issue by mrwallace888** [ange-yaghi/engine-sim#108]
Any attempt to get it in gear results in an instantaneous engine stall.

If 100 clutch is "in-gear" and 0 clutch is just revving freely, then if I shift it into gear, regardless of the amount of throttle, as soon as clutch goes up to just "1" (meaning in real life I just _barely_ lift off the clutch pedal), it's an instant stall.

The engine is literally undrivable and I don't know what I'm doing wrong.

Also, how do I test other engines instead of just a two-cylinder?

**Comment by DDev247** [comment]
The stock v-twin engine makes 16 horsepower. It won't move a whole car.

> Also, how do I test other engines instead of just a two-cylinder?  

Read wiki faq [here](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions).

**Comment by CoreoftheEarth** [comment]
This. I was going to make an issue on this but I wanted to wait to see if it wasn't just me. Spoiler alert: it wasn't.

**Comment by patriksramoss** [comment]
Same here. I have no idea what I'm doing wrong. Meanwhile, I watch other youtube videos where guys just switch gears without even touching Spacebar lmao

**Comment by shootie22** [comment]
I've been wondering the same question since v1.3a. I've gotten it working today after reading @DDev247 's comment, which is indeed what we're doing wrong. Switch to a different engine and it will work. Interesting cause for "issue" though, the engine not having enough HP to move the car.

**Comment by Abdullah-Ajeebi** [comment]
> Same here. I have no idea what I'm doing wrong. Meanwhile, I watch other youtube videos where guys just switch gears without even touching Spacebar lmao

the spacebar is meant for smoothing gear transitions
