### ISSUE TITLE
Error with opening 

### ISSUE THREAD

**Issue by Knifeisuk** [ange-yaghi/engine-sim#109]
In the FAQ it doesnt mention how to fix this 
in the error im getting 
main(5): error P0010: Unexpected token
main(6): error P0010: Unexpected token

the code being

import "engine_sim.mr"
import "engines/audi/i5.mr"

set_engine(
engine: Audi 2.2 inline 5()
)

**Comment by TheMispeled** [comment]
engine: audi_i5_2_2L

**Comment by Jckf** [comment]
Please read [the FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) for instructions on how to change the engine.
