### ISSUE TITLE
engine sim is taking global input

### ISSUE THREAD

**Issue by alec-jensen** [ange-yaghi/engine-sim#11]
so the app is taking input, even when its not in focus. i feel like it should only accept input if it is in focus.

**Comment by ange-yaghi** [comment]
I'll disable global inputs, I needed it for my own purposes but I can imagine it being annoying for other people

**Comment by naikrovek** [comment]
Duplicate of #4.  Can issues be merged?

**Comment by ange-yaghi** [comment]
Should be fixed now.
