### ISSUE TITLE
MAKE A PROPER X64 WINDOWS BUILD AND MAKE A RELEASE

### ISSUE THREAD

**Issue by choi303** [ange-yaghi/engine-sim#115]
Please make a proper windows release so we can test it quick. Whole build and CMAKE stuff makes it annoying.

**Comment by alexmyczko** [comment]
make it build on linux and macOS?

**Comment by ange-yaghi** [comment]
Uhh... there is a release already isn't there?

**Comment by alexmyczko** [comment]
yes plenty: https://github.com/ange-yaghi/engine-sim/tags

**Comment by choi303** [comment]
Shifting is not working in the Windows releases. I'm depressing clutch and shifting to first and as soon as I'm coming up from clutch even if I use the space bar to release smoothly. Engine stalls immediately. But other than that, all the information sound exhaust waves are great man!

> Uhh... there is a release already isn't there?

**Comment by choi303** [comment]
I tried to build the source because I wanted to change my engine to something bigger.

**Comment by l0wigh** [comment]
Try another engine. If it makes enough horsepower it will not stall. The 2 cylinders engine isn't powerful enough for the stock gear ratio. It's NOT a compilation problem at all

**Comment by cmdrscotty** [comment]
> I tried to build the source because I wanted to change my engine to something bigger.

You don't need to build the source just to change engines.

Look in the assets (might be assets/parts library) as of 0.1.7a there's a file called main.mr this is where you change what engine it's using.
