### ISSUE TITLE
Building on !Windows (eg. FreeBSD/Linux)

### ISSUE THREAD

**Issue by ehaupt** [ange-yaghi/engine-sim#118]
I'm aware that the `README.md` states that this project currently only builds on Windows but nevertheless I would love to see it compile on other operating systems such as FreeBSD or Linux.

Here is a build log on FreeBSD 13.1-RELEASE amd64 with clang 13.0.0. It might be easy to fix.

Please let me know if I can assist in providing access to a test/dev environment.

[engine-sim-typescript.txt](https://github.com/ange-yaghi/engine-sim/files/9359572/engine-sim-typescript.txt)

**Comment by alexmyczko** [comment]
look https://github.com/ange-yaghi/engine-sim/pull/112

**Comment by ehaupt** [comment]
Thanks @alexmyczko!

**Comment by TheMispeled** [comment]
maybe reactOS

**Comment by TheAwesome98-Real** [comment]
> maybe reactOS

ReactOS is Windows-compatible, so it already works

**Comment by suburbGira** [comment]
reactos isn't complete enough to run everything yet though is it?

**Comment by TheAwesome98-Real** [comment]
no but that’s not this programme’s fault

**Comment by Calinou** [comment]
Related to https://github.com/ange-yaghi/engine-sim/issues/2. Once Linux support is added, *BSD support should be easy to add.
