### ISSUE TITLE
Debugging custom .mr engine files?

### ISSUE THREAD

**Issue by avirtopeanu-ionos** [ange-yaghi/engine-sim#119]
Hello, fantastic work on this simulator!

I'm trying to build a custom V3 engine, with one piston on one cylinder bank (with a cylinder head of `generic_small_engine_head` of 50cc chamber volume) and two pistons on the opposite cylinder bank (with a cylinder head of `generic_small_engine_head` of 100cc chamber volume)

Obviously things may not make sense but they're not supposed to, this is just for fun

Problem is the sim crashes instantly when I try to boot it up. Is there a way to debug my engine asset file in order to at least launch the sim? I don't care if the engine runs poorly 

You can also find my .mr file attached

[v3.zip](https://github.com/ange-yaghi/engine-sim/files/9366278/v3.zip)

**Comment by Jckf** [comment]
[The FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) has some simple instructions how to identify faults.

**Comment by Jckf** [comment]
You're crankshaft is designed for a 2 stroke engine. One full cycle of a 4 stroke engine is not 360 degrees, but 720. That means the distance between each crank journal, cam lobe, and spark should be: 720 / 3 = 240 deg.
