### ISSUE TITLE
Audi engine issue

### ISSUE THREAD

**Issue by Helthenoob** [ange-yaghi/engine-sim#124]
idk why but iam not able to open that Audi i5 engine. It keep showing error

**Comment by tobster786** [comment]
i have the same issue with it

**Comment by Tybernn** [comment]
if you have "audi_i5_2_2L" in the set_engine in the main file

**Comment by Jckf** [comment]
Hello.

Please have a look at [our FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) for instructions on how to change the engine and how to read error messages. If you still have issues afterwards, please post your error log here.
