### ISSUE TITLE
dodge charger

### ISSUE THREAD

**Issue by D-T-666** [ange-yaghi/engine-sim#125]
Just wanted to point out that this sim produces far far more realistic engine sound than [the new Dodge electric car](https://twitter.com/TwoSteele/status/1560119031432024064).

Disclaimer: this statement may turn out to be stupid.

**Comment by sujaldev** [comment]
discussions should be enabled so people can talk about stuff like this and not have to create an issue

**Comment by DDev247** [comment]
or just go to the discord

**Comment by Sk3leCreeper** [comment]
that. Just join the discord and chat in the related channels there, [https://discord.com/invite/chKreEmXw6](url)

**Comment by sujaldev** [comment]
yeah that would work too
