### ISSUE TITLE
cant open on windows 8.1

### ISSUE THREAD

**Issue by dafijo** [ange-yaghi/engine-sim#126]
When i try to open on my windows 8.1 i get Program error 0xc000007b and i am not sure how to fix this

**Comment by sujaldev** [comment]
from a quick google search about this error code, you might be running 32 bit windows...

**Comment by Jckf** [comment]
The error code indicates some sort of mixing of 32 and 64 bit. Make sure you're on 64 bit Windows and have not downloaded any missing DLL files from unknown sources.
