### ISSUE TITLE
Can we get more engines added overall even from older cars?

### ISSUE THREAD

**Issue by SallyTheUnknownMan** [ange-yaghi/engine-sim#128]
I know that the sim is incomplete but other than the engine configurator we should get more engines too

**Comment by SallyTheUnknownMan** [comment]
Also what's the BMW engine name?

**Comment by MilkMan1093** [comment]
> Also what's the BMW engine name?

M52B28

**Comment by SallyTheUnknownMan** [comment]
> > Also what's the BMW engine name?
> 
> M52B28
thanks bro
