### ISSUE TITLE
how to create a custom engine? Example: audi V10 5.2FSI

### ISSUE THREAD

**Issue by WhiteWolf4448** [ange-yaghi/engine-sim#129]
hello, I would like to create another engine like the Audi V10 5.2FSI or the BMW M70 or the VR6 AAA, is this possible?

**Comment by HawkHunt** [comment]
All these engines should be completely possible. Have a look at the prebuilt engines and try to create the engines you want.

**Comment by ISAKEM** [comment]
> hello, I would like to create another engine like the Audi V10 5.2FSI or the BMW M70 or the VR6 AAA, is this possible?

I am almost done with my 5.2 FSI so yes it is possible. All piston configurations as far as I am aware are possible.

**Comment by alexmyczko** [comment]
heh someone had the idea to put a small computer+speakers on a lower engine car... if someone does it, btw 30k visitors from https://www.reddit.com/r/cars/comments/wofb53/dont_have_car_miss_the_engine_noise/

**Comment by alexmyczko** [comment]
@WhiteWolf4448 did you look at the existing ones? https://github.com/ange-yaghi/engine-sim/tree/master/assets/engines

**Comment by Jckf** [comment]
[This wiki page](https://github.com/ange-yaghi/engine-sim/wiki/Creating-your-own-engine) will be expanded on in the future.
