### ISSUE TITLE
Missing engine

### ISSUE THREAD

**Issue by sujaldev** [ange-yaghi/engine-sim#13]
The video shows `CHEV 454 V8` but I can only find `Kohler CH750` in the source code? Has it been intentionally removed? If yes, could you give a hint on how to obtain an engine similar to that in the video, I tried editing the `assets/kohler_ch750.mr` file but sadly it does not work as intended. (I neither know C++ nor piranha).

I tried adding two more wires, a crankshaft, another exhaust and 2 more cylinder banks and then tried to bind it to the engine (class/enum/dictionary?) from what I could make out of the language but now it just won't open.

Thanks for this mind blowing project.

**Comment by Chalcedonity** [comment]
Yeah I too would like to know how to manipulate the parameters - having no experience in these languages. Anyone who could make some sort of UI would be a godsend

**Comment by BoogieHasFun** [comment]
try to build from https://github.com/ange-yaghi/engine-sim/tree/edba9a4940599222ca2e9c5acf7be8ccccc78592

**Comment by DDev247** [comment]
It wasn't removed.
It's under `assets\video-scripts\454-tuning` BUT it prob won't work great

**Comment by Hacker1245** [comment]
> It wasn't removed. It's under `assets\video-scripts\454-tuning` BUT it prob won't work great

when I try to run that engine it does not seem to work

**Comment by Chalcedonity** [comment]
> 

and how do you run the sim with that engine?

**Comment by Hacker1245** [comment]
> > 
> 
> and how do you run the sim with that engine?

Copied the file into assets/parts-library/engines then edited engines.mr and replaced the engine name.

**Comment by DerpyNinjaFrog** [comment]
You can also do it this way if you don't want to move files, and then if you want to change it later it's easier. In `assets\part-library\engines\engines.mr` add `public import "../../video-scripts/454-tuning/engine_01.mr"`. Then in `assets\test.mr`, change `engine: kohler_ch750` to `engine: video_engine_454_01()`. Whenever you want to change it just change that line. This will work for the other engines (e.g. engine_02 = `engine: video_engine_454_02()`). Make sure to add them to the engines script though.

**Comment by Hacker1245** [comment]
let me test that, wonder if I'm having issues because I'm running it through Wine

**Comment by Chalcedonity** [comment]
It worked for me, but performance is terrible, stuttering etc. I followed these steps

> You can also do it this way if you don't want to move files, and then if you want to change it later it's easier. In `assets\part-library\engines\engines.mr` add `public import "../../video-scripts/454-tuning/engine_01.mr"`. Then in `assets\test.mr`, change `engine: kohler_ch750()` to `engine: video_engine_454_01()`. Whenever you want to change it just change that line. This will work for the other engines (e.g. engine_02 = `engine: video_engine_454_02()`). Make sure to add them to the engines script though.

**Comment by Hacker1245** [comment]
> It worked for me, but performance is terrible, stuttering etc. I followed these steps

so I see I'm not the only one.

**Comment by Chalcedonity** [comment]
> > It worked for me, but performance is terrible, stuttering etc. I followed these steps
> 
> so I see I'm not the only one.

And does it sort of repeat for you as well, almost like an echo, and the fps counter fluctuates? I get a smooth simulation when time warping so I believe it is to do with optimisation

**Comment by Hacker1245** [comment]
> > > It worked for me, but performance is terrible, stuttering etc. I followed these steps
> > 
> > 
> > so I see I'm not the only one.
> 
> And does it sort of repeat for you as well, almost like an echo, and the fps counter fluctuates? I get a smooth simulation when time warping so I believe it is to do with optimisation

Yep.

**Comment by Chalcedonity** [comment]
Okay glad we both have the issue. I'm new to all of this GitHub etc, so if the simulator was to be improved, is it only Ange who can do that? Like adding a terminal to change cylinder count etc. I.e do we just have to be patient or can we contribute as well?

**Comment by Hacker1245** [comment]
We can contribute as well by forking the repository and making a pull request, like the one that updated the readme.

**Comment by BoogieHasFun** [comment]
> Okay glad we both have the issue. I'm new to all of this GitHub etc, so if the simulator was to be improved, is it only Ange who can do that? Like adding a terminal to change cylinder count etc. I.e do we just have to be patient or can we contribute as well?

anyone can help out and modify open sourced code on github all they want via a fork, if they feel like the code should be on the main repo they can pull-request their changes on the main repo, and if the owner approves it, it will get merged to the main repo

in this case main repo is /[ange-yaghi](https://github.com/ange-yaghi)/engine-sim
a fork would look like /[Chalcedonity](https://github.com/Chalcedonity)/engine-sim

**Comment by DDev247** [comment]
> Okay glad we both have the issue. I'm new to all of this GitHub etc, so if the simulator was to be improved, is it only Ange who can do that? Like adding a terminal to change cylinder count etc. I.e do we just have to be patient or can we contribute as well?

Technically no, but yes. The only people that can merge pull requests are those with write permission.
As to the second portion, you can contribute by making said pull requests. I and Pooria are working on an editor for engines.

**Comment by Chalcedonity** [comment]
> > Okay glad we both have the issue. I'm new to all of this GitHub etc, so if the simulator was to be improved, is it only Ange who can do that? Like adding a terminal to change cylinder count etc. I.e do we just have to be patient or can we contribute as well?
> 
> Technically no, but yes. The only people that can merge pull requests are those with write permission. As to the second portion, you can contribute by making said pull requests. I and Pooria are working on an editor for engines.

That’s awesome really glad to hear it. Hope you guys do well

**Comment by Ghost8000** [comment]
> 

this one half worked for me, i imported the angine succesfully, but it won't run, anyways to fix the lagg issue just press N and scroll down with the mous wheel, setting the simulation speed between 3000 and 4000 worked for me even if the engine doesn't start

**Comment by Chalcedonity** [comment]
> > It worked for me, but performance is terrible, stuttering etc. I followed these steps
> 
> this one half worked for me, i imported the angine succesfully, but it won't run, anyways to fix the lagg issue just press N and scroll down with the mouse wheel, setting the simulation speed between 3000 and 4000 worked for me even if the engine doesn't start

Yeah I found that too, below 5000 it becomes 60fps for me

**Comment by sujaldev** [comment]
Marking as closed, since it has been resolved in the newer build. Thanks everyone for your help!
