### ISSUE TITLE
Single Cylinder doesnt want to run

### ISSUE THREAD

**Issue by HawkHunt** [ange-yaghi/engine-sim#130]
Basically, I am trying to get to grips with creating engines.

I made this little CRF250 engine but it just does not want to run,
I based a lot of the parts off of the Kohler engine so its not really a CRF250 engine but its close enough for me to learn.

I tried taking out timing, adding timing, lightening the crank, making the crank heavier (same with the flywheel)
I gave the starter more RPM, but it just doesnt run.

`import "engine_sim.mr"

units units()
constants constants()
impulse_response_library ir_lib()

private node wires {
    output wire1: ignition_wire();
}

label cycle(2 * 360 * units.deg)

public node singleCylinder_distributor {
    input wires;
    input timing_curve;
    input rev_limit: 5500 * units.rpm;
    alias output __out:
        ignition_module(timing_curve: timing_curve, rev_limit: rev_limit)
            .connect_wire(wires.wire1, 0 * units.deg);
}

public node CRF250F {
    alias output __out: engine;

    engine engine(
        name: "CRF250F",
        starter_torque: 50 * units.lb_ft,
        starter_speed: 1000 * units.rpm,
        redline: 3600 * units.rpm
    )

    wires wires()

    crankshaft c0(
        throw: 63 * units.mm / 2,
        flywheel_mass: 10 * units.lb,
        mass: 10 * units.lb,
        friction_torque: 10.0 * units.lb_ft,
        moment_of_inertia: 0.22986844776863666 * 0.5,
        position_x: 0.0,
        position_y: 0.0,
        tdc: constants.pi / 4
    )

    rod_journal rj0(angle: 0.0)
    c0
        .add_rod_journal(rj0)

    piston_parameters piston_params(
        mass: 100 * units.g,
        //blowby: k_28inH2O(0.1),
        compression_height: 1.0 * units.inch,
        wrist_pin_position: 0.0,
        displacement: 0.0
    )

    connecting_rod_parameters cr_params(
        mass: 90.0 * units.g,
        moment_of_inertia: 0.0015884918028487504,
        center_of_mass: 0.0,
        length: 4.0 * units.inch
    )

    cylinder_bank_parameters bank_params(
        bore: 71 * units.mm,
        deck_height: (4.0 + 1) * units.inch + 69 * units.mm / 2
    )

    intake intake(
        plenum_volume: 1.0 * units.L,
        plenum_cross_section_area: 10.0 * units.cm2,
        intake_flow_rate: k_carb(50.0),
        idle_flow_rate: k_carb(0.0),
        idle_throttle_plate_position: 0.96,
        throttle_gamma: 1.0
    )

    exhaust_system_parameters es_params(
        outlet_flow_rate: k_carb(300.0),
        primary_tube_length: 10.0 * units.inch,
        primary_flow_rate: k_carb(200.0),
        velocity_decay: 1.0,
        volume: 20.0 * units.L
    )

    exhaust_system exhaust0(
        es_params,
        audio_volume: 1.0,
        impulse_response: ir_lib.default_0
    )

    cylinder_bank b0(bank_params, angle: 0 * units.deg)
    b0
        .add_cylinder(
            piston: piston(piston_params, blowby: k_28inH2O(0.1)),
            connecting_rod: connecting_rod(cr_params),
            rod_journal: rj0,
            intake: intake,
            exhaust_system: exhaust0,
            ignition_wire: wires.wire1
        )

    engine
        .add_cylinder_bank(b0)

    engine.add_crankshaft(c0)

    harmonic_cam_lobe lobe(
        duration_at_50_thou: 160 * units.deg,
        gamma: 1.1,
        lift: 200 * units.thou,
        steps: 100
    )

    vtwin90_camshaft_builder camshaft(
        lobe_profile: lobe,
        lobe_separation: 114 * units.deg,
        base_radius: 500 * units.thou
    )

    b0.set_cylinder_head (
        generic_small_engine_head(
            chamber_volume: 50 * units.cc,
            intake_camshaft: camshaft.intake_cam_0,
            exhaust_camshaft: camshaft.exhaust_cam_0
        )
    )

    function timing_curve(1000 * units.rpm)
    timing_curve
        .add_sample(0000 * units.rpm, 50 * units.deg)
        .add_sample(1000 * units.rpm, 50 * units.deg)
        .add_sample(2000 * units.rpm, 50 * units.deg)
        .add_sample(3000 * units.rpm, 50 * units.deg)
        .add_sample(4000 * units.rpm, 50 * units.deg)

    engine.add_ignition_module(
        singleCylinder_distributor(
            wires: wires,
            timing_curve: timing_curve,
            rev_limit: 5000 * units.rpm
        ))
}
`

**Comment by HawkHunt** [comment]
Engine:

`import "engine_sim.mr"

units units()
constants constants()
impulse_response_library ir_lib()

private node wires {
    output wire1: ignition_wire();
    output wire2: ignition_wire();
    output wire3: ignition_wire();
    output wire4: ignition_wire();
    output wire5: ignition_wire();
    output wire6: ignition_wire();
    output wire7: ignition_wire();
    output wire8: ignition_wire();
}

public node honda_V4_Reversed {
    alias output __out: engine;

    wires wires()

    engine engine(
        name: "Honda VFR800_Reversed",
        starter_torque: 400 * units.lb_ft,
        redline: 5500 * units.rpm,
        fuel: fuel(
            max_turbulence_effect: 3.0,
            burning_efficiency_randomness: 0.5,
            max_burning_efficiency: 0.85)
    )

crankshaft c0(
        throw: 2 * units.inch,
        flywheel_mass: 15 * 2 * units.lb,
        mass: 40 * units.lb,
        friction_torque: 10.0 * units.lb_ft,
        moment_of_inertia: 0.22986844776863666 * 2,
        position_x: 0.0,
        position_y: 0.0,
        tdc: constants.pi / 4
    )

    rod_journal rj0(angle: contants.pi)

    c0
        .add_rod_journal(rj0)

    piston_parameters piston_params(
        mass: 780 * units.g,
        blowby: 0,
        compression_height: 1.640 * units.inch,
        wrist_pin_position: 0.0,
        displacement: 0.0
    )

    connecting_rod_parameters cr_params(
        mass: 685.0 * units.g,
        moment_of_inertia: 0.0015884918028487504,
        center_of_mass: 0.0,
        length: 6.135 * units.inch
    )

    cylinder_bank_parameters bank_params(
        bore: 4.25 * units.inch,
        deck_height: 9.8 * units.inch
    )


    chevy_bbc_stock_intake intake(
        carburetor_cfm: 650.0,
        idle_flow_rate_cfm: 0.007,
        idle_throttle_plate_position: 0.963,
        throttle_gamma: 1.5
    )

    exhaust_system_parameters es_params(
        outlet_flow_rate: k_carb(550.0),
        primary_tube_length: 10.0 * units.inch,
        primary_flow_rate: k_carb(90.0),
        velocity_decay: 1.0, //0.5
        volume: 50.0 * units.L
    )

    exhaust_system exhaust0(es_params, audio_volume: 1.0, impulse_response: ir_lib.default_0)
    exhaust_system exhaust1(es_params, audio_volume: 0.1, impulse_response: ir_lib.default_0)

	cylinder_bank b0(bank_params, angle: -45 * units.deg)
    b0
		.add_cylinder(
            piston: piston(piston_params, blowby: k_28inH2O(0.2)),
            connecting_rod: connecting_rod(cr_params),
            rod_journal: rj0,
            intake: intake,
            exhaust_system: exhaust0,
            ignition_wire: wires.wire1
        )	
    
    engine
		.add_cylinder_bank(b0)

    engine.add_crankshaft(c0)

    chevy_454_stock_camshaft camshaft()
	
		b0.set_cylinder_head (
        chevy_bbc_peanut_port_head(
            intake_camshaft: camshaft.intake_cam_0,
            exhaust_camshaft: camshaft.exhaust_cam_0
        )
    )
	
	
    function timing_curve(1000 * units.rpm)
    timing_curve
        .add_sample(0000 * units.rpm, 50 * units.deg)
        .add_sample(1000 * units.rpm, 50 * units.deg)
        .add_sample(2000 * units.rpm, 50 * units.deg)
        .add_sample(3000 * units.rpm, 50 * units.deg)
        .add_sample(4000 * units.rpm, 50 * units.deg)

    engine.add_ignition_module(
        vFour90_distributor_Reversed(
            wires: wires,
            timing_curve: timing_curve,
            rev_limit: 9000 * units.rpm
        )
    )

}
`

**Comment by HawkHunt** [comment]
private import "engine_sim.mr"

units units()
label cycle(2 * 360 * units.deg)

public node chevy_bbc_distributor {
    input wires;
    input timing_curve;
    input rev_limit: 5500 * units.rpm;
    alias output __out:
        ignition_module(timing_curve: timing_curve, rev_limit: rev_limit)
            .connect_wire(wires.wire1, (0.0 / 8.0) * cycle)
            .connect_wire(wires.wire8, (1.0 / 8.0) * cycle)
            .connect_wire(wires.wire4, (2.0 / 8.0) * cycle)
            .connect_wire(wires.wire3, (3.0 / 8.0) * cycle)
            .connect_wire(wires.wire6, (4.0 / 8.0) * cycle)
            .connect_wire(wires.wire5, (5.0 / 8.0) * cycle)
            .connect_wire(wires.wire7, (6.0 / 8.0) * cycle)
            .connect_wire(wires.wire2, (7.0 / 8.0) * cycle);
}

public node chevy_sbc_distributor {
    input wires;
    input timing_curve;
    input rev_limit: 5500 * units.rpm;
    alias output __out: chevy_bbc_distributor(
        wires: wires,
        timing_curve: timing_curve,
        rev_limit: rev_limit
    );
}

public node vtwin90_distributor {
    input wires;
    input timing_curve;
    input rev_limit: 5500 * units.rpm;
    alias output __out:
        ignition_module(timing_curve: timing_curve, rev_limit: rev_limit)
            .connect_wire(wires.wire1, (0.0 / 8.0) * cycle)
            .connect_wire(wires.wire2, (3.0 / 8.0) * cycle);
}

public node vFour90_distributor {
    input wires;
    input timing_curve;
    input rev_limit: 9000 * units.rpm;
    alias output __out:
         ignition_module(timing_curve: timing_curve, rev_limit: rev_limit)
            .connect_wire(wires.wire1, (8.0 / 8.0) * cycle)
			.connect_wire(wires.wire2, (7.0 / 8.0) * cycle)
            .connect_wire(wires.wire3, (2.0 / 8.0) * cycle)
            .connect_wire(wires.wire4, (1.0 / 8.0) * cycle);
			
}
			
public node vFour90_distributor_Reversed {
    input wires;
    input timing_curve;
    input rev_limit: 9000 * units.rpm;
    alias output __out:
         ignition_module(timing_curve: timing_curve, rev_limit: rev_limit)
            .connect_wire(wires.wire1, (0.0 / 8.0) * cycle)
            .connect_wire(wires.wire8, (1.0 / 8.0) * cycle)
            .connect_wire(wires.wire4, (2.0 / 8.0) * cycle)
            .connect_wire(wires.wire3, (3.0 / 8.0) * cycle)
            .connect_wire(wires.wire6, (4.0 / 8.0) * cycle)
            .connect_wire(wires.wire5, (5.0 / 8.0) * cycle)
            .connect_wire(wires.wire7, (6.0 / 8.0) * cycle)
            .connect_wire(wires.wire2, (7.0 / 8.0) * cycle);

}

**Comment by finicu212** [comment]
what a coincidence, I just made this engine: https://catalog.engine-sim.parts/parts/13

could do with some timing tuning, I think

**Comment by HawkHunt** [comment]
Finicu212 your version is 1000 times better than mine. I got it to run and rev, the crank was 90 deg out of position. I advanced it to 45 degrees infront of the bank angle and it fired up.
My engine is terrible compared to yours though! I have so much more to learn

**Comment by finicu212** [comment]
This is my first engine where I did everything properly. with a simulator as new as this, we're all beginners. I really recommend using the Discord as a learning resource, everyone in this community is very helpful, you can try out all the different engines shared in the #engine-sharing text channel, and ask for more help on the #support channel

**Comment by Jckf** [comment]
Please join our Discord for further assistance.
