### ISSUE TITLE
How to build an engine

### ISSUE THREAD

**Issue by MDV110207** [ange-yaghi/engine-sim#132]
I got the tiniest idea on how to make/code one

**Comment by alexmyczko** [comment]
look at these https://github.com/ange-yaghi/engine-sim/tree/master/assets/engines

**Comment by sujaldev** [comment]
[This](https://github.com/Enginette/enginette) might be helpful to you

**Comment by Jckf** [comment]
[This wiki page](https://github.com/ange-yaghi/engine-sim/wiki/Creating-your-own-engine) will be expanded on in the future.
