### ISSUE TITLE
App does not start 

### ISSUE THREAD

**Issue by Diougo** [ange-yaghi/engine-sim#133]
When i start the app it just closes, and i dont get any error in  the error log file.

**Comment by HawkHunt** [comment]
Did you modify any files or is it  "clean"?

**Comment by Diougo** [comment]
> Did you modify any files or is it "clean"?

It´s a clean install.

**Comment by sujaldev** [comment]
If you post your system specifications, that might be helpful

**Comment by Diougo** [comment]
i7-8650U
16gb ram
gtx 1060 6gb

**Comment by Diougo** [comment]
> If you post your system specifications, that might be helpful

i7-8650U
16gb ram
gtx 1060 6gb

**Comment by sujaldev** [comment]
OS?

**Comment by Diougo** [comment]
> OS?

Windows 11 Pro version 21H2

**Comment by sujaldev** [comment]
does the error log file have anything?

**Comment by Diougo** [comment]
> does the error log file have anything?
It has nothing.

**Comment by Jaxeman09** [comment]
> > does the error log file have anything?
> 
> It has nothing.

When you open it does it say there is a missing file or does it just not open???

**Comment by lepton0004** [comment]
does nothing. it peeks then sleeps

**Comment by Jckf** [comment]
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27
