### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by Etigopro** [ange-yaghi/engine-sim#135]
It says that It cannot continúe because d3dx11_43.dll and VCRUNTIME140_1.dll was not found

**Comment by zacharyd3** [comment]
If you rename d3dx11d_43.dll to d3dx11_43.dll it opens for me. Still crashes immediately but it helps at least lol.

**Comment by sujaldev** [comment]
Try installing/updating directx and if still doesn't fix the problem, downloading these dlls individually and placing them in the bin folder might fix it.

**Comment by simonfei123** [comment]
Downloaded d3dx11d_43.dll and I got this error:
![image](https://user-images.githubusercontent.com/15989959/185832937-e2feb740-ac6f-4315-8f4a-8badac41b4c0.png)

**Comment by trapicki** [comment]
I had to download the DirectX Runtime from https://www.microsoft.com/en-us/download/details.aspx?id=35 (hint from https://answers.microsoft.com/en-us/windows/forum/all/when-i-install-a-game-it-d3dx1143dll-is-missinghow/c801f2ec-7327-4643-a1f5-d74d23d3635b), now it runs.

_Note:_ _renaming/copying_ D3DX11d_43.dll **did not work**!
