### ISSUE TITLE
No vulkan-1.dll?

### ISSUE THREAD

**Issue by asepfadry** [ange-yaghi/engine-sim#138]
I tried to open the program, but the message "The code execution cannot proceed because vulkan-1.dll was not found. Reinstalling the program may fix this problem." I have downloaded the latest version
![Screenshot (117)](https://user-images.githubusercontent.com/111675837/185778091-9625d6f5-1124-4f89-8af6-c57772c72e3a.png)
.

**Comment by sujaldev** [comment]
Check https://github.com/ange-yaghi/engine-sim/issues/91

**Comment by Jckf** [comment]
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/45
