### ISSUE TITLE
App opens, then closes without running

### ISSUE THREAD

**Issue by MusicAddict99** [ange-yaghi/engine-sim#141]
engine-sim-app will open, show whit screen and loading icon on mouse, then close out. No errors in the log. Had to rename several of the d3d...... files to get to this point. On Win10 laptop, intel celeron chip, 64 bit system. Any ideas for a fix? TIA! Looking forward to getting to nerd out as a motorhead! It is a clean download btw (other than the renamed files)

**Comment by Jckf** [comment]
If you have been messing with the DLL files, then there is really no telling what's the issue any more. Please start with a clean release and report the initial issue that made you start renaming things in the first place.

**Comment by MusicAddict99** [comment]
> If you have been messing with the DLL files, then there is really no telling what's the issue any more. Please start with a clean release and report the initial issue that made you start renaming things in the first place.

Initial issue with clean download is app would not open at all and provided error “d3dx11_43.dll not found”. When looking at file names, this file was named “D3DX11_43.dll”. I renamed it to “d3dx11_43.dll” and now the app will open, load for about 5 seconds, and then shut down.

**Comment by Jckf** [comment]
What kind of system are you running this on? Windows' default file system NTFS is case-insensitive, so that casing of the filename should not matter, as far as I know.

**Comment by MusicAddict99** [comment]
> What kind of system are you running this on? Windows' default file system NTFS is case-insensitive, so that casing of the filename should not matter, as far as I know.

I am using the default Windows 10 files system

**Comment by Jckf** [comment]
And did you clone the repo using Git for Windows or downloading a zip from Github, or have you used Git inside WSL?

**Comment by MusicAddict99** [comment]
> And did you clone the repo using Git for Windows or downloading a zip from Github, or have you used Git inside WSL?

I downloaded the .zip file directly from GitHub

**Comment by Jckf** [comment]
Alright. I ask because directories created through WSL will have case-sensitivity enabled, but that's not it then.

**Comment by Jckf** [comment]
The answer here is to install the DirectX runtime.
