### ISSUE TITLE
How do you let go of the clutch slowly???

### ISSUE THREAD

**Issue by Montydog9** [ange-yaghi/engine-sim#15]
I cant seem to let go of the clutch smoothly causing the engine to stall and shut off

**Comment by Minerite231** [comment]
same

**Comment by macluxHD** [comment]
keep spacebar pressed and then release shift to move the clutch smoothly

**Comment by DDev247** [comment]
The base engine (v-twin) is too weak for the vehicle simulation. 16 horsepower won't get you anywhere.
Also there is no way currently to let go of the clutch smoothly.

**Comment by BoogieHasFun** [comment]
> The base engine (v-twin) is too weak for the vehicle simulation. 16 horsepower won't get you anywhere. Also there is no way currently to let go of the clutch smoothly.

we aren't simulating vehicles, and you can let go of the clutch smoothly

**Comment by DDev247** [comment]
When you wnt to switch gears and 'drive' then it is a vehicle simulation. Ange explained it in the video.

**Comment by BoogieHasFun** [comment]
> When you wnt to switch gears and 'drive' then it is a vehicle simulation. Ange explained it in the video.

didn't know that.

**Comment by ange-yaghi** [comment]
I'll add a note about slowly releasing the clutch in the README
