### ISSUE TITLE
App crash without any error

### ISSUE THREAD

**Issue by Fabbro03** [ange-yaghi/engine-sim#153]
I've already used the software in another pc (i7-11700k and GTX1660) but in my brand new alienware m15 r7 doesn't start.

Firstly it opens a white window, and after maybe 5 seconds it crashes without any displayed error, even in the error_log.log.

To help investigate the issue there is my hw configurations:
- CPU: Intel i7-12700H
- iGPU: Intel Iris Xe Graphics (driver ver. 31.0.101.3222)
- dGPU: Nvidia RTX3060 Laptop (driver ver. 516.94)
- OS: Win 11 22H2 (build 22622.575)

P.S. Can it be an issue with the hybrid architecture of Intel 12th gen?

**Comment by TheMispeled** [comment]
go into error_log.txt and tell me what is in it

**Comment by Fabbro03** [comment]
Maybe are you saying "error_log.log" and, as I mentioned before, it is completely empty.

**Comment by Abdullah-Ajeebi** [comment]
is it 0.1.5 or above

**Comment by kn0n** [comment]
i've seen this happen when you dont put the name of an engine correctly

**Comment by Potato22** [comment]
check if your import paths are using / instead of \
##the app will crash when:
1. the imported engines are typed incorrectly/wrong path (double check filenames)
2. `set_engine()` is calling an engine that doesn't exist (double check filenames and paths)
3. `use_x_theme()` is calling a theme that doesn't exist (double check filenames and paths)

**Comment by Jckf** [comment]
There are 3 things that I know can cause a white screen followed by a crash and no error messages.
1. A cylinder bank without a head.
2. A cylinder bank that hasn't been added to the engine instance.
3. A cylinder without a crank journal.

Please join our Discord server if you require further assistance.
