### ISSUE TITLE
Cannot open due to "vulkan-1.dll" not being found

### ISSUE THREAD

**Issue by devonchase03** [ange-yaghi/engine-sim#158]
Not really sure what is going on, downloaded straight from the source and it doesn't want to load and throws that error message.

**Comment by 123jcatjoseph** [comment]
I am having the same issue

**Comment by SirKnightTG** [comment]
This is a file that comes with your graphics driver. Install the latest graphics driver and it should work, unless you have a really old GPU that doesn't support Vulkan.

**Comment by Jckf** [comment]
Correct answer given by @SirKnightTG: The Vulkan runtime should come included with your graphics card drivers.
