### ISSUE TITLE
How to I create my own engine

### ISSUE THREAD

**Issue by SwordMan64** [ange-yaghi/engine-sim#161]
I want to create my own engine but im not sure how.

**Comment by finicu212** [comment]
[check the FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) and the [parts catalog](https://catalog.engine-sim.parts/) for example engines. you can create your own engine by creating .mr scripts, and importing and initializing them into main.mr.

**Comment by Jckf** [comment]
[This wiki page](https://github.com/ange-yaghi/engine-sim/wiki/Creating-your-own-engine) will be expanded on in the future.
