### ISSUE TITLE
error: code cannot be executed because d3dx11_43.dll was not found

### ISSUE THREAD

**Issue by bruh69420420** [ange-yaghi/engine-sim#166]
i dont know if this is my computer but i cant use any of the versions because of this!!

**Comment by Jckf** [comment]
There are [multiple other tickets for this problem](https://github.com/ange-yaghi/engine-sim/issues?q=is%3Aissue+d3dx11). Please have a read through them and see if any of the suggested solutions work for you.

**Comment by sujaldev** [comment]
Maybe this one should be added to the FAQ given how common it is
