### ISSUE TITLE
Errors when switching engines.

### ISSUE THREAD

**Issue by Heliosynthis** [ange-yaghi/engine-sim#169]
I just downloaded the game today, wanted to switch engines. So I followed the tutorial on the FAQ. Now it doesn't boot and it throws up errors in the log. My code:
import "engine_sim.mr"
import "engines/kohler/kohler_ch750.mr"

import "engine_sim.mr"
import "engines/bmw/M52B28.mr"

set_engine(
    engine: bmw_distributor()
)

The errors:
main(5): error T0010: Argument with incompatible type specified; valid conversion not found
main(5): error V0040: Input not connected
main(5): error V0040: Input not connected

Any ideas?

**Comment by Heliosynthis** [comment]
Alright. I thought that "bmw_distributor" was the internal name. Thank you!!!

**Comment by Heliosynthis** [comment]
Huh? The engine cuts out if I let go of the starter, even after holding it for more than 10 seconds.

**Comment by Jckf** [comment]
The node "bmw_distributor" is (probably) the distributor, not the engine ;)

**Comment by quinnzaballa** [comment]
Just find an public node with **alias output __out: engine;** then copy the name beside the public node
