### ISSUE TITLE
Infinte RPM and 6100+ MPH

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [ange-yaghi/engine-sim#172]
![Engine Sim _ AngeTheGreat _ v0 1 8a 27_01_44 08_13_28 م](https://user-images.githubusercontent.com/111107624/186728451-f96b7034-1918-47c9-aebd-a1925870939d.png)

**Comment by bruh69420420** [comment]
he said that if you make the simulation frequency too low the game becomes unstable and that happens

**Comment by Jckf** [comment]
Correct. Setting the simulation frequency too low will cause it to become unstable and fail.
