### ISSUE TITLE
unable to change to V8

### ISSUE THREAD

**Issue by bruh69420420** [ange-yaghi/engine-sim#173]
i've tried to select the chevy but i dont know how to do it.. the error log says this: 

main(7): error P0010: Unexpected token
main(8): error P0010: Unexpected token
main(5): error IO0010: Could not open file

**Comment by Jckf** [comment]
Please have a look at [this wiki page](https://github.com/ange-yaghi/engine-sim/wiki/How-to-change-engines). It includes a video if you prefer that.

**Comment by bruh69420420** [comment]
it says how to change to the audi but i dont know how to change to the chevy engine

**Comment by bruh69420420** [comment]
it only shows how to change to audi engine not chevy

**Comment by Abdullah-Ajeebi** [comment]
its the same but redo it with the chevy engine

**Comment by bruh69420420** [comment]
how? i tried it like this

import "engine_sim.mr"
import "engines/kohler/kohler_ch750.mr"
import "engines/audi/i5.mr"
import "engines/bmw/m52b28.mr"
import "engines/chev/truck_454.mr"
set_engine(
    engine: chev_truck_454()
)
but it doesnt work i dont know what node i put for the set engine

**Comment by Abdullah-Ajeebi** [comment]
should have been like this

import "engine_sim.mr"
import "engines/kohler/kohler_ch750.mr"
import "engines/audi/i5.mr"
import "engines/bmw/M52B28.mr"
import "engines/chevrolet/engine_03_for_e1.mr"
import "engines/chevrolet/chev_truck_454.mr"

set_engine(
    engine: chev_truck_454()
)
