### ISSUE TITLE
Can't turn down simulation frequency

### ISSUE THREAD

**Issue by guibrites** [ange-yaghi/engine-sim#174]
I have a laptop and I want to turn down the frequency without a mouse scroll cause I don't have a mouse

I have coded a little script that allows me to emulate scroll up and down by pressing F1 and F2 and it works fine for most applications (including CAD), but it's not working for this simulator

Is there a way around this issue? My PC can only run engines up to 3 cylinders without stuttering, it'd be nice to lower the simulation frequency.

**Comment by ange-yaghi** [comment]
There will be a workaround in the next release. I'll get around to fixing the issue with laptops at some point.

**Comment by guibrites** [comment]
> There will be a workaround in the next release. I'll get around to fixing the issue with laptops at some point.

Great! Thank you so much, I'll look forward to it

**Comment by ange-yaghi** [comment]
You can set the simulation frequency in the .mr script for the engine now as a workaround
