### ISSUE TITLE
Change power and torque numbers

### ISSUE THREAD

**Issue by devonchase03** [ange-yaghi/engine-sim#177]
Is there any way to change the horsepower numbers and torque numbers effectively? I've looked, but it's hard to figure out.

**Comment by Jckf** [comment]
Engine power is a result of the engine's design. You don't define them directly.

**Comment by bruh69420420** [comment]
for me, all i do is change the starter torque and speed XD

**Comment by Jckf** [comment]
Please join our Discord for further assistance.
