### ISSUE TITLE
unable to run program

### ISSUE THREAD

**Issue by Polskiekulki** [ange-yaghi/engine-sim#180]
when i want to start program it show ,, cannot find vulkan-1.dll ,, newest version, reinstalling dont work
![obraz_2022-08-27_221703662](https://user-images.githubusercontent.com/92812228/187046632-aa6b89cf-f060-46d9-a822-6e621ecf4c31.png)
it say ,, _Code execution cannot continue because vulkan-1.dll was not found. Reinstalling the program may fix this problem._ "

**Comment by Nizarizhear** [comment]
[Uploading vulkan-1.zip…]()
Copy the "vulkan-1.dll" file inside the ZIP folder into the same folder as the game exe. (AKA put the dll file into the bin folder)

**Comment by Nizarizhear** [comment]
Download the 64-bit file in this website and inside the ZIP folder copy the dll file and put it into the same folder as the game exe file (bin folder) and change the name to "vulkan-1"
https://www.dll-files.com/vulkan-1.dll.html
