### ISSUE TITLE
Everything is glitchy

### ISSUE THREAD

**Issue by Nizarizhear** [ange-yaghi/engine-sim#181]
When i start the game it shows 4-6 FPS and buffer is 500-600 and every gauge needles are glitching. Engine makes noises after 4 seconds of engine start but it's also very laggy, I cannot tell if it's a software issue or i just run old hardware, the game functions normally and smoothly but it's the needles and engine sound that is very very glitchy. The whole system runs smoothly and in task manager it shows that it uses about 60-70 MB RAM.

The hardware i run with:
Intel HD Graphics 4000
Intel i5 3340-M
4 GB RAM
500 GB HDD
Windows 7 - Professional

**Comment by susrn** [comment]
Your igpu doesn't support vulkan.

**Comment by TheMispeled** [comment]
also your cpu is old, consider upgrading it

**Comment by Nizarizhear** [comment]
> Your igpu doesn't support vulkan.

Okay thanks for the info
