### ISSUE TITLE
Game crashing without any error written on the error.log file

### ISSUE THREAD

**Issue by dontcheckmyemail** [ange-yaghi/engine-sim#182]
I do know that there is a person who had opened a ticket for the same reason but i wanted to do some research on the problem my own way. So when i try to open the game, the game crashes without any error on the error log. I do not know if it my system requirements (Intel Core i5 2500 CPU w/ Intel HD 2000 iGPU) or a problem within the files (note: i do have the vulkan-1.dll file) other that it does not work.

**Comment by susrn** [comment]
you can see the spec requirements for your system [here](https://www.intel.com/content/www/us/en/support/articles/000005524/graphics.html) under Intel Core Processors tab you can see at the bottom of the table your igpu only supports up to DirectX 10.1 and no Vulkan support, so you can't run this simulation.
