### ISSUE TITLE
Feature Request: Asymmetrical Lobe Profile (Camshaft)

### ISSUE THREAD

**Issue by MaximumGam** [ange-yaghi/engine-sim#185]
symmetric cam lobes does a really great job and works as it should! 
but my engine needs some asymmetric lobes... 
will it happen soon ? :P 
![profile_types](https://user-images.githubusercontent.com/75767302/187088174-e8ba25dd-8126-4c06-a923-952c6202203d.jpg)

**Comment by ange-yaghi** [comment]
Already supported
