### ISSUE TITLE
Now can you please make a fully detailed 3D vehicle editor (I do have a feeling it's gonna be 999x even better than Automation)

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#187]
I want to build a 2020 Gavril D-Series (the name of truck from BeamNG I am finally familiar with since the final quarter of 2020) sooooo bad!!! Or even 2004 (official, not that DFA one)
You want to be able customize every visual part you want (other than paint color(s), tires, wheels, etc., like side windows, wheelbase, length, position, etc.), and even add your own parts and stuff to current vehicle build/project. NEVER ANY EXCEPTIONS!!
Also make your own background(s)
Sadly, I am getting very upset of MotorSim 3 and that poor dev @TheBrainSphere he's taking a long time to make it!!😪😪

**Comment by Jorras** [comment]
You do understand how much effort and time does it take to make something on a scope like this?

**Comment by OcileCollection** [comment]
> You do understand how much effort and time does it take to make something on a scope like this?

Well, he needs to cure cancer before that...
