### ISSUE TITLE
ONLY THE STUPID KOHLER ENGINE LOADS, AND I CAN'T SWITCH TO OTHER ENGINE BUT HOW TO!!😪

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#188]

**Comment by quinnzaballa** [comment]
Bro read the FAQ page. i know its weird but its really basic 👨 first find the engines *.mr example 

- engines\audi\i5.mr
- You'll find this in the assets folder in the engine-sim folder

1. find the main.mr in the assets folder, Open the main.mr put it aside.
2. find the engine *.mr (we are using audi\i5.mr for example)
3. replace the ### engines/kohler/kohler_ch750.mr | To | engines\audi\i5.mr **from main.mr** 
4. now open the engine *.mr _i5.mr for example_ now find or search an public node that has **alias output __out: engine;** and the connecting public node has a name which has to be the **set_engine** name, copy it to 

_set_engine(
    kohler_ch750()
)_

Rename into

**_set_engine(
    audi_i5_2_2L()
)_**

save and start the sim.

**Comment by Jckf** [comment]
☝️ https://github.com/ange-yaghi/engine-sim/wiki/How-to-change-engines

**Comment by jim4800frank** [comment]
> ☝️ https://github.com/ange-yaghi/engine-sim/wiki/How-to-change-engines

STILL LOADS THAT CRAPPY SAME DEFAULT GEARLESS ENGINE!!😪😡
