### ISSUE TITLE
YEAH WE DO NEED THE ABILITY TO CHANGE ENGINE IN THE APP DIRECTLY AND CREATE YOUR OWN!!!😪

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#189]

**Comment by quinnzaballa** [comment]
Whoa there buckaroo chill with your "caps lock". It might be hard. why not look at the assets\part-library and open each .mr to understand the each nodes. scripting might not be your interest but when you learn it. its easier. enginette might be a good chance for you but its on development heres the link

here - [https://github.com/Enginette/enginette](url)

**Comment by Jckf** [comment]
In-app engine changing has already been requested multiple times, and engine creation is just a matter of documentation - which is coming :)
