### ISSUE TITLE
Can not run more than 6 cilinders engine

### ISSUE THREAD

**Issue by TWHoster** [ange-yaghi/engine-sim#191]
I have a computer with 32 gb of ram and an I7 7th gen. It is a gaming computer but the simulator lags a lot when I try to simulate more than 6 cilinders. I see that the all the CPU is used. Is there a way to improve it?

**Comment by quinnzaballa** [comment]
Ram is useless at this point. its using minimal ram usage. try lowering simulation rate? hold N and scroll down to 5000hz

**Comment by Jckf** [comment]
[FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions)
