### ISSUE TITLE
Engine stalls as soon as I slightly disable the clutch

### ISSUE THREAD

**Issue by nico-qwer** [ange-yaghi/engine-sim#193]
With the base engine (Kohler CH750), when trying to switch speeds from neutral, and following the FAQ, the engine stalls as soon as the clutch reaches more than 0. I don't know if its a skill issue on my part, but I don't know.  

Here is a video of the issue:

https://user-images.githubusercontent.com/100895510/187239333-735f356a-8a25-411a-87bc-513700c5c22a.mp4

**Comment by ronangaillard** [comment]
Same problem here

**Comment by Positrons** [comment]
> The ch750 is a 30 hp woodchipper engine, and you're trying to make it drive a big truck. It's not going to work :)

Yeah since this is the case, maybe it would save a lot of confusion by changing the default engine to one that is capable of changing gear without stalling.

**Comment by Jckf** [comment]
> Yeah since this is the case, maybe it would save a lot of confusion by changing the default engine to one that is capable of changing gear without stalling.

I agree, and it has been suggested a couple of times before. It's up to @ange-yaghi though.
