### ISSUE TITLE
sim stuttering despite only using ~15% of CPU

### ISSUE THREAD

**Issue by thejodkb** [ange-yaghi/engine-sim#194]
Running a complicated modded engine and despite the sim stuttering (only somewhat stable running at about 4000hz) my task manager says it (the sim) is only using about 12-15% of CPU (out of about 16-18% total CPU usage). I have already set it to high priority and no changes. Any ideas?

**Comment by Jckf** [comment]
If you have an 8 core (or 4 core/8 thread) CPU, then 12.5% = 100% on one core. If you're running Windows, you can change your Task Manager's CPU graph to "Logical Processors" to better visualize it.

![image](https://user-images.githubusercontent.com/1040070/187299279-f309c86e-ed28-42fc-9eda-b0268742755b.png)

**Comment by thejodkb** [comment]
![image](https://user-images.githubusercontent.com/112435347/187300206-30baac45-e3ad-4496-a6f2-b2e5bcd7a531.png)
Alright so it appears to be using up my 2nd core. I presume this is because for what ever reason the sim is locked to only using one?

**Comment by thejodkb** [comment]
CPU is a AMD Ryzen 3600X (6 core, 12 thread). CPU 3 and 4 so both threads of core 2 are being used.

**Comment by Jckf** [comment]
The sim is using multiple threads, but the physics calculations are all on a single one, aplitting this work into multiple threads is non-trivial. The 3600x should be able to handle anything up to and including a v8 without issues though. Anything past that will probably require that you reduce the simulation frequency.

**Comment by thejodkb** [comment]
Alright, sounds good and thanks for the help.
