### ISSUE TITLE
add a different version of the simulator for old CPUs with no vulkan compatibility

### ISSUE THREAD

**Issue by dontcheckmyemail** [ange-yaghi/engine-sim#195]
Before i had made a post, and from seeing the result, it seems that my processor's iGPU is too outdated to have compatibility with vulkan/game, so can it be possible to do a version coded in a different way so vulkan is not necessary for old-CPUs like I?

**Comment by klertimalaj** [comment]
Hey! My iGPU also didnt support vulkan and this simulator needs the dll file. Just download the vulkan dll file from www.dll-files.com. search vulkan and it will appear to download. Also dont forget to paste it to bin folder and rename it vulkan-1 if the name is different. Worked for me!

**Comment by AndreeDanieldAS** [comment]
@klertimalaj it worked for me too and do the same like you did, but when I run the .exe again, its open and close immediately and  when I open error.log, nothing in there. Do you experience it too?

**Comment by dontcheckmyemail** [comment]
@klertimalaj i have the same problem as @AndreeDanieldAS, it does open but seconds later, it closes. I also did add the vulkan-1.dll file

**Comment by dontcheckmyemail** [comment]
Also in one of the post i did, a person said that due to my iGPU being too outdated (since it's a Intel HD 2000) it cannot take in charge vulkan files.

Here look:https://www.intel.ca/content/www/ca/en/support/articles/000005524/graphics.html

**Comment by klertimalaj** [comment]
> @klertimalaj it worked for me too and do the same like you did, but when I run the .exe again, its open and close immediately and when I open error.log, nothing in there. Do you experience it too?



For me it works fine, been running it a long time and never closed. What engine are you running? Maybe the processor cant handle the simulation and the freq. should be changed.

**Comment by klertimalaj** [comment]
> Also in one of the post i did, a person said that due to my iGPU being too outdated (since it's a Intel HD 2000) it cannot take in charge vulkan files.
> 
> Here look:https://www.intel.ca/content/www/ca/en/support/articles/000005524/graphics.html

It is a bit old. I will do a bit of research and will try to help you, but i think the vulkan file in the bin folder is more of a file that is just to get checked by the .exe that requires it to run. So basically downloading it is a bit of a bypass. If you have the chance, try considering a cheap graphic card. I dont think this iGPU will run the app but i will try to help u.

**Comment by dontcheckmyemail** [comment]
@klertimalaj  Alright, thank you.

**Comment by klertimalaj** [comment]
> @klertimalaj Alright, thank you.


There is something u could try. Try dowloading the older versions of the vulkan file on the website and putting them on the bin folder. And then run the app. Try them all and also try updating your drivers.

**Comment by dontcheckmyemail** [comment]
@klertimalaj Sadly, i tried and it does not work

**Comment by AndreeDanieldAS** [comment]
> For me it works fine, been running it a long time and never closed. What engine are you running? Maybe the processor cant handle the simulation and the freq. should be changed.

maybe its because my laptop too old for this stuff like you said, thank you for your time to help.

![image](https://user-images.githubusercontent.com/80676749/187681495-9409fc17-fa2e-4f7e-9367-93f09ec16995.png)
![image](https://user-images.githubusercontent.com/80676749/187681815-8ef17f9e-e1b6-41aa-a07c-2168e13cb917.png)

**Comment by klertimalaj** [comment]
> > For me it works fine, been running it a long time and never closed. What engine are you running? Maybe the processor cant handle the simulation and the freq. should be changed.
> 
> maybe its because my laptop too old for this stuff like you said, thank you for your time to help.
> 
> ![image](https://user-images.githubusercontent.com/80676749/187681495-9409fc17-fa2e-4f7e-9367-93f09ec16995.png) ![image](https://user-images.githubusercontent.com/80676749/187681815-8ef17f9e-e1b6-41aa-a07c-2168e13cb917.png)

Always happy to help. Notify me if you find a way.

**Comment by Calinou** [comment]
That IGP is indeed too old to have any form of Vulkan support. Your best bet is to try a software Vulkan implementation such as Lavapipe. There are Windows builds of it available at https://github.com/pal1000/mesa-dist-win, but I haven't gotten them to work so far.

**Comment by dontcheckmyemail** [comment]
@Calinou oh ok thanks

**Comment by GRBaset** [comment]
I tested this on a VMware Fusion VM (no Vulkan, OpenGL 4.1), and after copying `vulkan-1.dll` to the `bin` directory it ran, though not very well. So Vulkan is clearly not required, maybe it uses OpenGL instead, and your OpenGL version is too old. 

From what I see, HD Graphics 3000 supports GL 3.1 on Windows, and GL 3.3 on Linux (because of newer drivers), so one suggestion would be to try it on Linux with Wine (it works fine on my Iris Pro 6200 iGPU, though that one supports Vulkan on Linux), you can use Bottles as a GUI.

**Comment by Jckf** [comment]
I can confirm that the current version of the sim in fact does **not** require Vulkan at all. It only requires the DLL file, because the underlying game engine supports both DirectX and Vulkan. The sim however is currently using DirectX.
