### ISSUE TITLE
Dyno Issue

### ISSUE THREAD

**Issue by AtlasUltimate** [ange-yaghi/engine-sim#197]
Using the dyno RPM control, you can force an engine WAY past its redline and send multiple pistons and your HP readouts into the next dimension. 
![image](https://user-images.githubusercontent.com/50212397/187359809-31ffac44-28c3-461b-99bf-57e1e8dc0a20.png)

**Comment by Hacker1245** [comment]
"It's not a bug, it's a feature", but in all seriousness yeah it would be nice if it was capped to some reasonable level.

**Comment by ange-yaghi** [comment]
Don't have any intention of "fixing" this and it's intentional
