### ISSUE TITLE
SDL2.dll file was not found

### ISSUE THREAD

**Issue by Prem160902** [ange-yaghi/engine-sim#200]
While installing the software, the program showed an error saying, "_The code execution can't be processed because **SDL2.dll** was not found. Reinstalling the program may fix this problem._"

![Screenshot 2022-08-30 173940](https://user-images.githubusercontent.com/108966597/187434572-5a4caa8f-9d5f-41a7-ad3b-abc3133b9e62.png)

**Comment by Jckf** [comment]
Extract the zip file before running the program.
