### ISSUE TITLE
Gear Ratios

### ISSUE THREAD

**Issue by enkynakamura** [ange-yaghi/engine-sim#203]
Hi,
I installed version 0.19.A and couldn't change the gear ratios, I also took existing scripts where there were included custom gear ratios but they don't seem to go even though the script creator himself in one of his published videos was clear that the gear ratios was customized and properly running. I don't understand why here locally it is not possible to run script with customized gear ratios and transmission.
Any ideas?
Thanks a lot

**Comment by Jckf** [comment]
In addition to the `set_engine()` call in your main.mr file, you also have to include a `set_transmission()` call. Have you done this?

**Comment by enkynakamura** [comment]
Thank You so much! It finally works, i did the same for vehicle so to have correct values for aerodynamic and vehicle mass.

**Comment by Calinou** [comment]
@enkynakamura You can close this issue as it's resolved :slightly_smiling_face:
