### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by SplendideMendax** [ange-yaghi/engine-sim#204]
https://github.com/ange-yaghi/engine-sim/blob/6c6b4f317473b728d8a6c0cc64d0644b445bd355/es/constants/units.mr#L73

I think it is Pa not kPa
also Bar added would be nice (100000 * Pa)

**Comment by ange-yaghi** [comment]
Pretty sure it's kPa, please refer to the Wikipedia article about atmospheric pressure: https://en.wikipedia.org/wiki/Atmospheric_pressure
