### ISSUE TITLE
Crashes with no error code.

### ISSUE THREAD

**Issue by boomaboom0818** [ange-yaghi/engine-sim#209]
I downloaded a fresh new copy and I checked all the import paths and they all seem to be alright. but it instantly crashes when I open the application.

**Comment by Jckf** [comment]
Is there anything in error_log.log?

**Comment by XxEduardoMTz** [comment]
having the same problem! And no, error_lo.log is blank.

**Comment by quinnzaballa** [comment]
Do you use custom engine *.mr?

**Comment by boomaboom0818** [comment]
I didn't change anything yet. Its a fresh new copy

**Comment by haohaoh4** [comment]
Same problem. There is even nothing in error log.

**Comment by NomsterDude** [comment]
Same problem, blank error_log.txt

**Comment by Jckf** [comment]
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27
