### ISSUE TITLE
More cylinders

### ISSUE THREAD

**Issue by YoungDev06** [ange-yaghi/engine-sim#21]
I tried to edit the engine file but idk what .mr is, is there a way you guys can add a default file to add cylinders so its actually working ?

**Comment by DogeSkii** [comment]
do this in discord not in GitHub issues

**Comment by YoungDev06** [comment]
> do this in discord not in GitHub issues

Its an issue, the engine cant support gear one

**Comment by DogeSkii** [comment]
> > do this in discord not in GitHub issues
> 
> 
> 
> Its an issue, the engine cant support gear one

that's YOUR engine, not a source problem

**Comment by YoungDev06** [comment]
> > > do this in discord not in GitHub issues
> > 
> > 
> > Its an issue, the engine cant support gear one
> 
> that's YOUR engine, not a source problem

its the DEFAULT engine that comes with it, its a source problem.

**Comment by OmegaPlatinumRain** [comment]
> > > > do this in discord not in GitHub issues
> > > 
> > > 
> > > Its an issue, the engine cant support gear one
> > 
> > 
> > that's YOUR engine, not a source problem
> 
> its the DEFAULT engine that comes with it, its a source problem.

The DEFAULT engine only makes 18 hp as its modeled after a lawnmower engine. The weight of the simulated vehicle is around the weight of a chevy truck

**Comment by Jckf** [comment]
Having the ch750 as the default engine might have been a bad decision, based on the number of people who get confused when shifting doesn't work, but that's up to Ange.

As for adding more cylinders to an engine, I'll note that down as a request for documentation. It's only natural that a project like this would need good documentation, but we haven't gotten around to it yet. It's coming though.
