### ISSUE TITLE
How to edit vehicle parameters?

### ISSUE THREAD

**Issue by ForwardMotion55** [ange-yaghi/engine-sim#218]
So I know enough about C++ to change simple parameters of certain things, I just can't seem to find where vehicle parameter files are.

I'm looking to change only the weight, I haven't got a straight answer (to the vehicle stalling due to lack of power), other than using a different engine, then again no one is asking the right question.

So I'll make this simple, are vehicle parameters changeable? If so, where can I find the file? 

Thank you in advance!

**Comment by Jckf** [comment]
You can change vehicle parameters by creating your own "vehicle node" and loading it using `set_vehicle()`. Have a look at some of the existing uses of this, like [this Porsche](https://catalog.engine-sim.parts/parts/54) for instance.

**Comment by ForwardMotion55** [comment]
Awesome thank you so much!

**Comment by ForwardMotion55** [comment]
> You can change vehicle parameters by creating your own "vehicle node" and loading it using `set_vehicle()`. Have a look at some of the existing uses of this, like [this Porsche](https://catalog.engine-sim.parts/parts/54) for instance.

Perfect thank you!
