### ISSUE TITLE
Wont start on win11

### ISSUE THREAD

**Issue by numer076** [ange-yaghi/engine-sim#222]
When I try to open the .exe it says, the d3dx11_43.ddl is missing. I redownloaded it and it still didnt work.

**Comment by R3dst0ne** [comment]
This problem is already addressed in the FAQ.
Take a look at [this](https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files).

**Comment by numer076** [comment]
> This problem is already addressed in the FAQ. Take a look at [this](https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files).

Thanks that was the thing is was searching for.
