### ISSUE TITLE
Switching License to GPL2

### ISSUE THREAD

**Issue by b0okle** [ange-yaghi/engine-sim#223]
I think this project needs to be licensed in GPL2 or GPL3. A project this big and unique shouldn't be in MIT, since any big tech would just copy and paste it into their work, and you can't do anything about it. If it's under GPL, you can sue them.

**Comment by ange-yaghi** [comment]
I'm not interested and more importantly don't have the means to sue anyone, especially not a large company. I don't really trust that GPL will deter anyone determined to use the code without permission
