### ISSUE TITLE
RPM hold doesn't care about engine redline.

### ISSUE THREAD

**Issue by Martorad** [ange-yaghi/engine-sim#224]
Using the engine hold feature, I can increase the RPM infinitely, presumably until an integer overflow.
\
![image](https://user-images.githubusercontent.com/54896741/187860684-e66ba8b2-7649-46cb-a896-5daacc6ccfd6.png)

**Comment by Jckf** [comment]
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/197
