### ISSUE TITLE
Help i've reached Infinite RPM and it doesn't start the program now :(

### ISSUE THREAD

**Issue by Goni2007** [ange-yaghi/engine-sim#226]

**Comment by DDev247** [comment]
Maybe provide more detail?
We don't know what you did wrong just by the title.

**Comment by Jckf** [comment]
Start by [looking at the error log](https://github.com/ange-yaghi/engine-sim/wiki/How-to-read-the-error-log).

**Comment by Boeing-737-800** [comment]
This might be an issue with the game itself, just reinstall it or [look at the error log](https://github.com/ange-yaghi/engine-sim/wiki/How-to-read-the-error-log)

**Comment by lordhoward2005** [comment]
Two questions
How?
What engine were you using?

**Comment by Jckf** [comment]
No feedback from issue owner in 1 month. Closing.
