### ISSUE TITLE
How to remove the 7000 ish rpm rev limeter on the bmw engine?

### ISSUE THREAD

**Issue by WayOfTheWorld** [ange-yaghi/engine-sim#230]

**Comment by Jckf** [comment]
Rev limit is controlled by the `rev_limit` argument passed to the ignition module. In the M52B28 you can find it on line 342. There is also an argument passed to the engine itself, that sets the tachometer scale, called `redline` on line 180.

**Comment by WayOfTheWorld** [comment]
Thanks a lot man!
