### ISSUE TITLE
Licensed Dependencies

### ISSUE THREAD

**Issue by RedlineTriad** [ange-yaghi/engine-sim#233]
When I looked at the repositories, I noticed that there are submodules that don't specify a license.
Not an expert on licenses, but it would probably be good to add license to those too, otherwise, doing basically anything with them is forbidden.

**Comment by Delaunay** [comment]
The modules with missing license are:

* simple-2d-constraint-solver
* csv-io

piranha got the MIT License on the master branch but the submodule has not been updated to use this branch yet.

@ange-yaghi  can you confirm that the `csv-io` and `simple-2d-constraint-solver` are licensed under MIT ?

Thanks

**Comment by ange-yaghi** [comment]
I've updated them all and yes they do all use MIT
