### ISSUE TITLE
I can't launch my game

### ISSUE THREAD

**Issue by tinini03** [ange-yaghi/engine-sim#236]
when I launch my game this gives me an error (0xc000)

**Comment by simix23** [comment]
it gives me an error too (0x0000007b)

**Comment by tinini03** [comment]
> it gives me an error too (0x0000007b)
(Yes that's it)

**Comment by Jckf** [comment]
Please give us some more information about your system.
 * Windows version
 * 32 or 64 bit
 * Type of CPU
 * Amount of memory
 * Type of graphics card

**Comment by tinini03** [comment]
> Please give us some more information about your system.
>  * Windows version
>  * 32 or 64 bit
>  * Type of CPU
>  * Amount of memory
>  * Type of graphics card

sorry i can't answer you for the moment i don't have my pc

**Comment by LuckyLion1378** [comment]
I don't know exactly how difficult this would be, but I'm sure there's people, like myself included, dying to play this but can't due to the fact they're on Mac. please, if it is easy, try adding Mac support?

**Comment by LuckyLion1378** [comment]
I have this too when I try running it on parallels windows 11 when on my MacBook Air M1.

**Comment by 4AGE12** [comment]
> Please give us some more information about your system.
> 
> * Windows version
> * 32 or 64 bit
> * Type of CPU
> * Amount of memory
> * Type of graphics card

i have the same 0x0000007b issue 
specs are 
i7-6600U
16gb Ram
Intel HD graphics 520

**Comment by Jckf** [comment]
The error code indicates some sort of mixing of 32 and 64 bit. Make sure you're on 64 bit Windows and have not downloaded any missing DLL files from unknown sources.
