### ISSUE TITLE
my game crash after a few second i open it:(

### ISSUE THREAD

**Issue by dat0207** [ange-yaghi/engine-sim#238]
pls help me,i really like and impressed with this game

**Comment by Jckf** [comment]
Have you made any changes to the game files, or is this a fresh copy?

**Comment by dat0207** [comment]
I didn't do anything to the game yet

**Comment by NomsterDude** [comment]
I have a fresh copy and it shows a blank white screen before crashing. Blank error log.

**Comment by Jckf** [comment]
Closing as presumed duplicate of https://github.com/ange-yaghi/engine-sim/issues/27
