### ISSUE TITLE
My game won't launch

### ISSUE THREAD

**Issue by NoxynoJoestar** [ange-yaghi/engine-sim#239]
When I launch the game a system error launches and says to me: "Could not execute the code because VBRUNTIME140_1.dll was not found. Reinstalling the program may fix this problem." I read the frequently asked questions and I found my error I installed Visual C++ and I restarted my computer and reinstalled the "game". I tried to launch it and it gives me the same error.

**Comment by Jckf** [comment]
The solution to this is in [the FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions) :)

**Comment by NoxynoJoestar** [comment]
ok I will try thx

**Comment by NoxynoJoestar** [comment]
I already did that and it didn't work
