### ISSUE TITLE
Feature request: Slowly releasable clutch

### ISSUE THREAD

**Issue by BuiltWithBytes** [ange-yaghi/engine-sim#24]
Feature request: Add a way to be able to slowly release the clutch, to have a chance to try smaller engines that otherwise stall out.

**Comment by Hary309** [comment]
Hold the space while releasing the shift, it should release the clutch slowly.

**Comment by Chalcedonity** [comment]
It does but still stalls it, just me?

**Comment by Hary309** [comment]
Yeah, the engine it too weak to move the vehicle.

**Comment by BuiltWithBytes** [comment]
Oh, I didn’t see that before. Thanks
