### ISSUE TITLE
Low FPS and high latency

### ISSUE THREAD

**Issue by adrix5521** [ange-yaghi/engine-sim#241]
When using the default engine (Kohler CH750) the FPS counter goes all the way up to V-Sync limit, but when I change the engine to literally ANYTHING but the default I get around 15fps, +500ms latency and the audio gets buggy and messed up. I have 16GB RAM, NVIDIA GTX 1050Ti and Intel i7-8750H so I don't think it's my computer's fault. I don't have any idea what could cause it, my drivers are up to date.

Kohler engine:
![image](https://user-images.githubusercontent.com/112776582/188283376-0b42f32f-eabd-4b0b-9ee3-1f339f8d8a9f.png)

Any other engine:
![image](https://user-images.githubusercontent.com/112776582/188283408-4aef113e-175d-4367-88fd-b476e6b21c25.png)

**Comment by kentweinroth** [comment]
I've been having a similar issue with latency except my frame rate is fine. For me, the latency keeps fluctuating between zero and max.

**Comment by Jckf** [comment]
The 8750H is a 45 watt laptop part. It most definitely is your CPU's "fault". Try reducing the simulation frequency as described in the FAQ.

**Comment by adrix5521** [comment]
> The 8750H is a 45 watt laptop part. It most definitely is your CPU's "fault". Try reducing the simulation frequency as described in the FAQ.

I'll try it out later, thank you!

**Comment by adrix5521** [comment]
So I tried it and it did help with FPS, latency is still high and audio is still messed up. When I set the frequency too low and try to rev up the engine, RPM goes up to "infinite rpm". I guess the cpu is just too weak for this.

**Comment by LexonBlackzz** [comment]
Try to put the priority to High, or close every app except the ones you also use. I have a Ryzen 5 4500U which almost has the same horse power as your 8750H and I get 60 FPS on most engines

**Comment by Jckf** [comment]
Look at [this issue](https://github.com/ange-yaghi/engine-sim/issues/243). The user solved it by plugging in his charger. This probably changed the power plan from "Battery Saver" or "Balanced" to "High performance".

**Comment by adrix5521** [comment]
> Look at [this issue](https://github.com/ange-yaghi/engine-sim/issues/243). The user solved it by plugging in his charger. This probably changed the power plan from "Battery Saver" or "Balanced" to "High performance".

That was the first thing I tried. All the laptops perform better when plugged in. It did not work for me.

**Comment by Jckf** [comment]
We know that the simulator is resource intensive, and this looks to be an issue either with your system or your expectations of your system, so I'm closing this ticket as it Probably ™ isn't a problem with the sim itself. Feel free to join our Discord server and ask if anyone else has had similar problem or have any suggestions on how to deal with it though.
