### ISSUE TITLE
Unstable latency

### ISSUE THREAD

**Issue by kentweinroth** [ange-yaghi/engine-sim#243]
The game works fine, but sometimes it displays an abnormal amount of latency despite having a good frame rate. I've tried adjusting the simulation frequency, but it doesn't seem to have any effect. I am running this on a Ryzen 7 5800H with an Nvidia GeForce RTX 3060 and 16 GB RAM using Windows 11.
![Screenshot 2022-09-03 173021](https://user-images.githubusercontent.com/106708528/188288305-74876c14-9518-425a-90ed-8b66eb660ab9.png)

**Comment by Jckf** [comment]
Sudden spikes in latency should in theory correspond to spikes in CPU load or dips in overall system performance (ie. throttling). Since we're talking about a laptop part, it's very likely that the system is dynamically adjusting performance to stay within a certain power or temperature window.

**Comment by EMREOYUN** [comment]
Same issue at RTX 3050, i5-11400H, 8GB, and Windows 11
This especially happens when running high-power engines.

**Comment by kentweinroth** [comment]
I think I figured out the problem...this happens when I attempt to run the program on battery power. Plugging my laptop in immediately fixed it. Thanks for your help!

**Comment by kentweinroth** [comment]
> Same issue at RTX 3050, i5-11400H, 8GB, and Windows 11 This especially happens when running high-power engines.

This might seem obvious, but try running the program with your laptop plugged in if you aren't doing so already.
