### ISSUE TITLE
d3dx11_43.dll not found

### ISSUE THREAD

**Issue by WhoAsked6358** [ange-yaghi/engine-sim#246]
I keep trying to run the program, but this keeps happening. I reinstalled it multiple time.

**Comment by leothemecanics** [comment]
same here

**Comment by Nelisdevelopus** [comment]
Same error here,

Running this on windows 11 21H2, on an Acer Swift 3 SF314-511 with an Intel Core I5-1135G7 with Xe graphics.

**Comment by Nelisdevelopus** [comment]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/93952500/188429735-45ed4a80-7251-47b9-8085-ed828dd29525.png">


> Same error here,
> 
> Running this on windows 11 21H2, on an Acer Swift 3 SF314-511 with an Intel Core I5-1135G7 with Xe graphics.

**Comment by Jckf** [comment]
Missing DLL files is addressed in the FAQ: https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files
