### ISSUE TITLE
High FPS and high and unstable latency

### ISSUE THREAD

**Issue by pnowojski** [ange-yaghi/engine-sim#247]
I have Ryzen 5900x and from the example engines I can only run the 2 cylinder one. Even for Audi i5 I have to decrease the fidelity to increase FPS to stable ~140. However even then latency is constantly spiking between 100 and a couple of hundreds/1000s, with audio being completely out of sync.

Is this normal expected behaviour? Others have reported similar audio issues on weaker machines and combined with low FPS.

**Comment by Jckf** [comment]
No this is not expected. It sounds like your system is performing much worse than it should. I personally run the sim on a 3700x and a 3800x, and neither have trouble with any of the included engines. I suggest verifying that your computer is operating normally by running some benchmarks and comparing them to other systems, and ensuring that no background tasks are interfering.

**Comment by pnowojski** [comment]
Thanks for the feedback, at least now I know there is an issue. I will try to look deeper, however I haven't noticed any performance problems in other games.

**Comment by pnowojski** [comment]
Huh, it turned out that somehow my PC was in the energy saving mode, despite it being a desktop not a laptop 🤷 Thanks @Jckf for confirming that I should look for something on my end.
