### ISSUE TITLE
Throttle position way too high at start

### ISSUE THREAD

**Issue by mryesmanjones** [ange-yaghi/engine-sim#253]
in 1.19 the throttle seems to be at almost maximum at idle. For example, if an engine's redline were to be at 8k, the rpms would be at 6.5-7k at idle. I don't know what the issue is, and I haven't tampered with any of the standard engines included in the sim.

**Comment by mryesmanjones** [comment]
Also I have reinstalled it and the issue wasn't fixed

**Comment by Jckf** [comment]
This is an issue with the particular engine you're using. It was made for v0.1.8 or earlier. Increase the idle throttle position to reduce idle speed.
