### ISSUE TITLE
DLL file not found

### ISSUE THREAD

**Issue by Puggoz** [ange-yaghi/engine-sim#254]
When started, d3dx11_43.dll was not found. I have tried downloading multiple versions, but with the same problem.
![image](https://user-images.githubusercontent.com/112920706/188543943-8356f706-62f3-4c37-8db1-ead5594bdd6d.png)

**Comment by Jckf** [comment]
https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files
