### ISSUE TITLE
APP CRASH WHEN PROVIDE ENGINE SAMPLES ARE LOADED 

### ISSUE THREAD

**Issue by mposha** [ange-yaghi/engine-sim#26]
Application crashes upon launch when files(engine1-4) stored in assets/video-scripts/455-tunning folder are loaded

**Comment by AyrA** [comment]
Next to the executable should be an `error_log.log` file. Copy the contents and paste here

**Comment by mposha** [comment]
> Next to the executable should be an `error_log.log` file. Copy the contents and paste here

test(6): error R0010: Undefined node type

**Comment by BoogieHasFun** [comment]
the engine your trying to load node's name is not correct, you can find node names inside the engines .mr file
example of what a node name looks like: 
![image](https://user-images.githubusercontent.com/76754631/184147293-d49ac189-07a3-4214-96a6-d412eae15fb8.png)

**Comment by Chaleuri** [comment]
In the `assets` folder there is a file named `test.mr`.

In that file, there are imports at the top. Make sure to import all the engines you want.

Example:

    import "engine_sim.mr"
    import "part-library/part_library.mr"
    import "video-scripts/454-tuning/engine_01.mr"
    import "video-scripts/454-tuning/engine_02.mr"
    import "video-scripts/454-tuning/engine_03.mr"
    import "video-scripts/454-tuning/engine_04.mr"


Now if I want to use the engine_03, then I need to change the set_engine's engine to that node's name.

Inside of the engine_03.mr:

    ...
        output wire8: ignition_wire();
    }
    
    public node video_engine_454_03 {
        alias output __out: engine;
    
        wires wires()
    
        engine engine(
            name: "Chev. 454 V8",
    ...

There is this line, which one's name we need:

    public node video_engine_454_03 {

Copy its name, in this example it's: `video_engine_454_03`, and change the test.mr file set engine's engine value to it.

Like this:

    set_engine(
        engine: video_engine_454_03()
    )

I don't know if this is how it should work but this way the engine_03 will load.

Hope this helped.

**Comment by mposha** [comment]
> the engine your trying to load node's name is not correct, you can find node names inside the engines .mr file example of what a node name looks like: ![image](https://user-images.githubusercontent.com/76754631/184147293-d49ac189-07a3-4214-96a6-d412eae15fb8.png)

![image](https://user-images.githubusercontent.com/64099244/184197576-7f5d8f9b-ab85-4ced-b26c-b1e6f019fc0a.png)
this is all thats in the engines.mr file

**Comment by mposha** [comment]
> 

heeeeeeeeey this resolved the issue thanks, is there any documentation on the working of the app so that i can know such?

**Comment by BoogieHasFun** [comment]
> > the engine your trying to load node's name is not correct, you can find node names inside the engines .mr file example of what a node name looks like: ![image](https://user-images.githubusercontent.com/76754631/184147293-d49ac189-07a3-4214-96a6-d412eae15fb8.png)
> 
> ![image](https://user-images.githubusercontent.com/64099244/184197576-7f5d8f9b-ab85-4ced-b26c-b1e6f019fc0a.png) this is all thats in the engines.mr file

btw i meant by the engine you downloaded .mr file
