### ISSUE TITLE
Simulator crashes after displaying blank white screen.

### ISSUE THREAD

**Issue by NomsterDude** [ange-yaghi/engine-sim#263]
I have a fresh download of the v1.10 build folder.

When I run it, the file instantly opens up a window with a blank white screen. This screen shows up for 2 seconds roughly before it closes.

The error_log.txt file is blank, no changes have been made.

**Comment by Jckf** [comment]
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27
