### ISSUE TITLE
Does this run on wine?

### ISSUE THREAD

**Issue by jansaternus** [ange-yaghi/engine-sim#266]
I don't have Windows so i use CrossOver so i want to check if this software can run on wine.

**Comment by DDev247** [comment]
Yes, it can, but you might encounter problems if you are on M1/M2 Mac.

An example running it through commands is:
`cd engine-sim-build_0_1_10/bin/`
`wine engine_sim_app.exe`

**Comment by jansaternus** [comment]
I have intel i7 mac

**Comment by jansaternus** [comment]
> Yes, it can, but you might encounter problems if you are on M1/M2 Mac.
> 
> An example running it through commands is: `cd engine-sim-build_0_1_10/bin/` `wine engine_sim_app.exe`

But can you run it trough crossover?
