### ISSUE TITLE
audio lag with external engines

### ISSUE THREAD

**Issue by tappeto001** [ange-yaghi/engine-sim#271]
I installed some engines a few days ago and every engine has audio lag problems, even after I lower simulation frequency and I still make 60 fps. I have a laptop with an Intel(R) Core(TM) i5-10500H CPU @ 2.50GHz, 16,0 GB RAM and a GTX 1650 max-q design

**Comment by Boeing-737-800** [comment]
I have the same issue!

**Comment by Abdullah-Ajeebi** [comment]
what is your rt/dt

**Comment by tappeto001** [comment]
Sorry what is rt/dt?

**Comment by tappeto001** [comment]
it's between 65 and 80. sorry if it took me so long to answer

**Comment by Boeing-737-800** [comment]
Try lowering your frequency to ~4000 hz

**Comment by tappeto001** [comment]
how can I lower it?

**Comment by Ozzy4201** [comment]
> what is your rt/dt

What is RT/DT?

**Comment by Abdullah-Ajeebi** [comment]
@tappeto001 n+scroll

**Comment by tappeto001** [comment]
I've already tried that but it doesn't work

**Comment by Jckf** [comment]
If reducing the frequency doesn't help, then your computer is not powerful enough to run the selected engine. More complex engines with more parts require more computing power to simulate.

**Comment by tappeto001** [comment]
Yes I also thought so, but I tried a v6 and it didn't work, after I tried a v12 and it worked perfectly

**Comment by Jckf** [comment]
It is possible that the v6 you're testing is using more exhaust systems than the v12, causing it to require more computing power even though it has fewer cylinders.

**Comment by tappeto001** [comment]
Oh oke. Is it normal that I make 60fps in both engines?

**Comment by tappeto001** [comment]
Oh oke. Is it normal that I make 60 fps on these engines even though the audio lags?
