### ISSUE TITLE
Variable exhaust pulse travel path length

### ISSUE THREAD

**Issue by rahatka** [ange-yaghi/engine-sim#272]
The problem is that it is not accounted for, as far as I can see.
Let's take an inline 3 as an example. If we merge all 3 exhaust ports into one system like this.

```
    exhaust_system_parameters es_params1(
     primary_tube_length: 300.0 * units.cm,
    *params*
    )

    exhaust_system exhaust0(es_params1, audio_volume: 0.3, impulse_response: ir_lib.default_0)

    b0
	.add_cylinder(
        ...
            exhaust_system: exhaust0,
        ...
        )
	.add_cylinder(
        ...
            exhaust_system: exhaust0,
        ...
        )
	.add_cylinder(
        ...
             exhaust_system: exhaust0,
        ...
        )
```
it doesn't take into account an exhaust port position along the header, therefore all pulses travel the same path and have the same distance between each other. Other harmonics are not present and the engine sounds unrealistically smooth and plain.
The only way to simulate this is to create 3 different exhaust systems with 3 different lengths which is not optimal and does not scale at all.

Is there a way to parametrise pulse emission position?

Like for example
```
	.add_cylinder(
        ...
             exhaust_system: exhaust0,
             exhaust_port_pos: 0 * units.cm,
        ...
        )
	.add_cylinder(
        ...
             exhaust_system: exhaust0,
             exhaust_port_pos: 10 * units.cm,
        ...
        )
	.add_cylinder(
        ...
             exhaust_system: exhaust0,
             exhaust_port_pos: 20 * units.cm,
        ...
        )
```
where `exhaust_port_pos` sets where the pulse got emitted along the `primary_tube_length`?

That would have been amazing and would make sound simulation even more realistic.

**Comment by ange-yaghi** [comment]
This has been added in v0.1.11a
