### ISSUE TITLE
Missing d3dx11_43.dll

### ISSUE THREAD

**Issue by JMan05** [ange-yaghi/engine-sim#273]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/84882996/189554900-39e1661d-a518-4c25-b51d-717990e1dd8f.png">
Missing d3dx11_43.dll

What does this mean and how can I fix it? I have reinstalled many times now so am resorting to asking for help

**Comment by Chris6ix** [comment]
The file you're missing is a DirectX file...so you would need to install (or reinstall) DirectX to fix this

**Comment by Jckf** [comment]
https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files
