### ISSUE TITLE
Can't find file

### ISSUE THREAD

**Issue by TimedCheetah267** [ange-yaghi/engine-sim#277]
When I go to lunch the app 4 file are always missing, PLZ HELP

**Comment by BoogieHasFun** [comment]
provide more info, then maybe someone can help.

i'd specify the files missing

**Comment by Jckf** [comment]
Don't try to run the sim from inside the zip file you downloaded. It must be extracted in its entirety.

If you're still having issues, have a look [here](https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files).
