### ISSUE TITLE
How do you change the engine?

### ISSUE THREAD

**Issue by Minerite231** [ange-yaghi/engine-sim#280]
How do you change the engine? because i want to swich to a more power full engine to get to higher gears than the default one.

**Comment by jansaternus** [comment]
The README.md has instructions of how to do it

**Comment by Minerite231** [comment]
ok thanks

**Comment by Minerite231** [comment]
it does not say how to change it

**Comment by jansaternus** [comment]
There is a link to a Q&A there

**Comment by Minerite231** [comment]
ok thanks now I know how
