### ISSUE TITLE
Latency Skyrockets

### ISSUE THREAD

**Issue by Jaxpet** [ange-yaghi/engine-sim#281]
Hey there, I'm recently having this issue when I'm using an engine like the Audi i5 or the Cosworth V10 I get very high latency it drops low, and it skyrockets to the 600 or 800s 
![image](https://user-images.githubusercontent.com/111883934/190376474-b448b03c-7abc-44ef-863a-1b2993dc773f.png)

**Comment by Abdullah-Ajeebi** [comment]
lower sim frequency

**Comment by Jckf** [comment]
Read the FAQ.
