### ISSUE TITLE
Vulkan_1.dll is missing and Crashes upon opening, with no error

### ISSUE THREAD

**Issue by Matty081** [ange-yaghi/engine-sim#284]
At first it said that vulkan_1.dll was missing. I solved it by installing the latest vulkan runtime.
I open the app again and it instantly crashges without showing an error.
Is it my graphics card that is not "worthy"?

**Comment by slamy9909** [comment]
i habe the same problem,cant find a way to fix it tho

**Comment by Jckf** [comment]
Read the FAQ.
