### ISSUE TITLE
Selecting engine assets doesn't work.

### ISSUE THREAD

**Issue by Jankstar11** [ange-yaghi/engine-sim#287]
When I try to select an engine file from C:\Users\user\Downloads\engine-sim-build_0_1_10a\engine-sim-build_0_1_10a\engine-sim-build_0_1_10a\assets\engines\ and then run it in the program, it doesn't work because when I open the app with the engine file I want, the engine doesn't show up. If I am doing it wrong, please let me know.

**Comment by Jckf** [comment]
Read the FAQ to learn about the error log.
