### ISSUE TITLE
The sounds cut off then does it over and over again

### ISSUE THREAD

**Issue by Unlea-exe** [ange-yaghi/engine-sim#289]
It keeps doing this and there's like a delay.

**Comment by Abdullah-Ajeebi** [comment]
screenshot please

**Comment by nonsensegone** [comment]
ususualy this is because of your simulation freq being too high, hold N and scroll down to lower the freq
Hope this helps
(P.S: You can tell if there is a performance problem by looking at the fps)

**Comment by Jckf** [comment]
Read the FAQ.
