### ISSUE TITLE
documentation on "units.mr" are unclear/how do i add it to my build of engine simulator?

### ISSUE THREAD

**Issue by xandersalarie** [ange-yaghi/engine-sim#294]
heya, so i have read the frequently asked questions, and i was wondering on how to actually implement units.mr and change from MPH to KPH. i tried a lot so far but i don't know how to do it as of now.

help is greatly appriciated

**Comment by ange-yaghi** [comment]
Look at the themes in assets/themes. You'll see examples of how to change the units.
