### ISSUE TITLE
Launching Error

### ISSUE THREAD

**Issue by PieMan28** [ange-yaghi/engine-sim#295]
Hey, I am totally new to this, I just saw the sim on Youtube and thought it was cool. I am trying to download the program but I keep getting an error that reads "The code execution cannot proceed because d3dx11_43.dll was not found." I tried reinstalling, but it did not fix my problem. Any help is appreciated!

**Comment by antmagl** [comment]
Just update DirectX and you should be fine

**Comment by PieMan28** [comment]
This sounds stupid but,
What is that?
How do I do that?

**Comment by Jckf** [comment]
Read the FAQ.
