### ISSUE TITLE
Enhancement | More app preferences

### ISSUE THREAD

**Issue by Teslahaha** [ange-yaghi/engine-sim#298]
I think what this engine simulator would benefit from are more app preferences. Currently you would need to manually adjust the simulation frequency and audio filters for every time you reload or switch engines, which is quite annoying and tedious. If there isn't something like this already, there should be settings that automatically sets the simulation frequency and audio filtering to whatever you've set in the .mr file.

**Comment by Jckf** [comment]
Default frequency and filter volumes can already be configured in the engine mr file. See https://github.com/ange-yaghi/engine-sim/blob/master/es/objects/objects.mr#L107
