### ISSUE TITLE
error:(0xc000007b)

### ISSUE THREAD

**Issue by undesirablejem** [ange-yaghi/engine-sim#299]
I tried to start engine-sim-app.exe and it said I was missing vulkan-1.dll. I solved the issue and this error popped up.
![306629991_1170345213892169_3748232523594213006_n](https://user-images.githubusercontent.com/114276929/192081237-d6c8109f-59f1-4fc2-a25a-2c4d6b3f1eb3.png)
If it helps I am running on Intel Integrated Graphics. Thanks for your help :)

**Comment by Jckf** [comment]
You have not solved the Vulkan issue. This error message means you have used the wrong DLL. Read the FAQ instead of downloading random DLLs from Google.
