### ISSUE TITLE
Latency starts at ~100, sky-rockets to 750, then slowly back down to ~100.

### ISSUE THREAD

**Issue by pxtential-spam** [ange-yaghi/engine-sim#307]
I've reinstalled, restarted, rebooted, troubleshooted everything. The latency keeps going up and down uncontrollably, even after moving the frequency up and down. Has nothing to do with my computer, obviously. Once it's above about 300, it makes the audio all choppy and gross. Tell me how to fix, please.

**Comment by sargonphin** [comment]
on my laptop I have the same thing when I reset the engine with Enter, and when the game window goes out of focus. i think it is a CPU performance thing, does it do it constantly? what's your CPU ?

**Comment by pxtential-spam** [comment]
It happens constantly. Intel Core i3, did run smoothly a while after initial install but no luck since then.

**Comment by pxtential-spam** [comment]
When I used the default Audi i5 engine, it only stuttered and lagged when the frequency was up high. Only started lagging constantly when I switched to the default Chevy truck engine, so you're most likely right. Thanks, y'all.
