### ISSUE TITLE
added all new engines, now sim bubbles  for a long time and does not load an engine

### ISSUE THREAD

**Issue by coding-without-knoledge** [ange-yaghi/engine-sim#312]
I made now folders in the engine folder to organize it a bit there are 13 of them. I renamed each engine file to its public node name. then I added import paths to the "main" file, there are 24 engines. I then try to launch the sim, it bubbles "program not responding" for a few minuets then loads. at the top where it says engine I get n/a. it is hard to trouble shoot because it takes so long to load between tries. 

here is a copy past of my "main" file. have I done something wrong

import "engine_sim.mr"
import "themes/default.mr"
import "engines/aircraft/merlin_v12.mr"
import "engines/aircraft/radial_5.mr"
import "engines/aircraft/radial_9.mr"
import "engines/audi/audi_i5_2_2L.mr"
import "engines/bmw/M52B28.mr"
import "engines/chevrolet/chev_truck_454.mr"
import "engines//chevrolet/engine_03_for_e1.mr"
import "engines//chevrolet/ls_v8.mr"
import "engines/dodge/.mr"
import "engines/ferrari/f136_v8.mr"
import "engines/ferrari/ferrari_412_t2_v12.mr"
import "engines/honda/honda_vtec_i4.mr"
import "engines/kohler/kohler_ch750.mr"
import "engines/lexus/lr_gue_v10.mr"
import "engines/motorcycle/harley_davidson_shovelhead.mr"
import "engines/motorcycle/hayabusa_i4.mr"
import "engines/motorcycle/honda_trx520.mr"
import "engines/other/even_fire_v6_90.mr"
import "engines/other/odd_fire_v6_90.mr"
import "engines/other/v6_60.mr"
import "engines/subaru/subaru_ej25.mr"
import "engines/subaru/subaru_ej25el.mr"
import "engines/subaru/subaru_ej25ol.mr"
import "engines/toyota/t2jz.mr"

use_default_theme()
main()
set_engine(
   kohler_ch750()
)

**Comment by Abdullah-Ajeebi** [comment]
yes and at 
`import "engines//chevrolet/engine_03_for_e1.mr"
import "engines//chevrolet/ls_v8.mr"`
there are two slashes between "engines" and "chevrolet"

and at 
`import "engines/dodge/.mr"`
you forgot to insert the file name

**Comment by coding-without-knoledge** [comment]
As my name suggests, I'm trying to mess around with the program with zero knowledge how to code

I know about the dodge one. I'm going to try make a 2.5L 4 cylinder out of a k car. I didn't think that it would cause any problems because I'm not putting it in to the "set engine" line. 

Does it cause problems just by existing?

It still doesn't open an engine.
this is what is in the error log after trying to open it once, what does this mean

radial_5(3): error IO0010: Could not open file
radial_9(3): error IO0010: Could not open file
main(16): error IO0010: Could not open file
main(17): error IO0010: Could not open file
main(18): error IO0010: Could not open file
radial_5(227): error R0010: Undefined node type
radial_5(234): error R0010: Undefined node type
radial_5(241): error R0010: Undefined node type
radial_5(248): error R0010: Undefined node type
radial_5(255): error R0010: Undefined node type
radial_9(299): error R0010: Undefined node type
radial_9(306): error R0010: Undefined node type
radial_9(313): error R0010: Undefined node type
radial_9(320): error R0010: Undefined node type
radial_9(327): error R0010: Undefined node type
radial_9(334): error R0010: Undefined node type
radial_9(341): error R0010: Undefined node type
radial_9(348): error R0010: Undefined node type
radial_9(355): error R0010: Undefined node type
subaru_ej25el(376): error R0010: Undefined node type
subaru_ej25ol(376): error R0010: Undefined node type

**Comment by ange-yaghi** [comment]
I don't suggest importing this many files since it will slow down startup significantly. It's best to keep just 1 import only.

**Comment by Abdullah-Ajeebi** [comment]
yes and also try reinstalling your simulator

**Comment by coding-without-knoledge** [comment]
Can I change the names of the folders that contain the engine files without issues along as I change the the part between the /

**Comment by coding-without-knoledge** [comment]
all the engines from the 2 videos work now but the engines that originally came with the sim aren't working, except the audi i5 as it was in one of the videos

i have tried it this way

import "engine_sim.mr"
import "themes/default.mr"
import "engines/bmw/M52B28.mr"

use_default_theme()
main()
set_engine(
    M52B28()
)

And this way
import "engine_sim.mr"
import "themes/default.mr"
import "engines/bmw/M52B28.mr"

use_default_theme()
main()
set_engine(
    M52B28()
)

is it just a brackets issue
