### ISSUE TITLE
New build is still broken

### ISSUE THREAD

**Issue by AngeSimIsBroke** [ange-yaghi/engine-sim#313]
I originally used build 0.1.10a and I had the issue where I didnt have file d3dx11_43.dll and vulkan-1.dll. I had downloaded the needed files and was getting the white screen and crashing. So now that the 0.1.11a build is out i'm having the same issue where it is a white screen and crashing. Now i haven't seen any new threads about this issue and when there is a thread it is instantly closed and referenced to #27 . But #27 is not resolved. Please don't instantly close this thread and actually fix the problem. 
P.S. Error Log is empty
PC Specs:

CPU:Intel(R) Xeon(r) CPU E5-1650 v4 @3.60 GHz
GPU:NVIDIA Quadro K2200

**Comment by semininja** [comment]
I am not a developer, but I can tell you this: duplicate threads for the same issue are useless, and complaining about duplicates being deleted is worse than useless - it's just noise. If you're experiencing #27, go add a +1 on #27 instead of opening #313 and whining.
