### ISSUE TITLE
Changing engines on build 0_1_11a

### ISSUE THREAD

**Issue by G-3R0** [ange-yaghi/engine-sim#314]
I am confused about how to change engines in build 0_1_11a:
I have looked for tutorials on how to do it in this build, but most of them date back to august / build 0_1_8a.
I am having problems because the main.mr files from the older and new version are different in that they have no section for telling the simulator wich engine to load.

**Comment by Kelmarit** [comment]
Likewise, maybe im just dumb

**Comment by AngeSimIsBroke** [comment]
All you have to do is follow the steps for 0_1_8a but after main() you have to paste this:
set_engine(
    audi_i5_2_2L()
)
Except you would change the engine to what you want.

**Comment by Jckf** [comment]
If the engine you're trying to use has no `main` node, then remove `main()` from the `main.mr` file, and replace it with regular old `set_engine()`.

Do _not_ include both.
