### ISSUE TITLE
issue with weak sound on build 0.1.11a

### ISSUE THREAD

**Issue by nexioss** [ange-yaghi/engine-sim#315]
hi, i play with the twincrant u10 by dacxl,
and with the latest build i get a really weak sound, and a pretty big latency too (frequancy set to 8000)

**Comment by Abdullah-Ajeebi** [comment]
especially when the engines revs below 1000rpm

**Comment by nexioss** [comment]
well for me its just i need that the sound is soo low that a bareilly hear anything. i need to pus my amp to 60 to hear anything

**Comment by Jckf** [comment]
This is a new feature that attenuates exhaust volume based on the exhaust system length. The default length is calculated from volume and diameter, and is probably very long if your volume ends up too low.
