### ISSUE TITLE
TDC at 0 make the game crash

### ISSUE THREAD

**Issue by GoostYTQC** [ange-yaghi/engine-sim#329]
title explained all

**Comment by Jckf** [comment]
This is not the case. You have likely made some other mistake. Please check out wiki to learn about the error log.

**Comment by GoostYTQC** [comment]
When you do it whit 0 * units.deg yes it does I am not a newbie so I know
how the sim work lol I haven compile the sim by myself soo

Le ven. 7 oct. 2022, 03 h 19, Jim C K Flaten ***@***.***> a
écrit :

**Comment by Jckf** [comment]
I tested it before responding to this ticket. Again, please check your error log.
