### ISSUE TITLE
d3dx11_43.dll missing

### ISSUE THREAD

**Issue by Clearsight555** [ange-yaghi/engine-sim#330]
When I try to launch the app, it says "The code execution cannot proceed because d3dx11_43.dll was not found. Reinstalling the program may fix this problem.

Can anyone help me resolve this issue?

**Comment by Jckf** [comment]
Please read the FAQ.

**Comment by jkadofo** [comment]
Specifically this part:

https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files
