### ISSUE TITLE
cannot load the V8 engine

### ISSUE THREAD

**Issue by Ghost8000** [ange-yaghi/engine-sim#34]
i tried to follow someone's advice to import the v8 engine (in my case it was engine 02 or video_engine_454_02)

i put this in the test.mr file     

import "engine_sim.mr"
import "part-library/part_library.mr"
import "video-scripts/454-tuning/engine_02.mr"

set_engine(
    engine: video_engine_454_02()
)

i was able to start the app and the angine is there however even if i have the ignition on and i run the starter, the engin won't run but just kinda missfire, i have also noticed that if i leave the simulation speed untouched it's very laggy and unstable, so i played with the simulation speed and after setting it between 3000 and 4000 it stopped lagging but the engine sadly still won't run.

**Comment by BuiltWithBytes** [comment]
This is because your computer cannot keep up with the simulation. Try lowering the simulation frequency.

**Comment by Ghost8000** [comment]
> This is because your computer cannot keep up with the simulation. Try lowering the simulation frequency.

lowered it below 3000 the engine won't run but it stayis at 60 fps so no lagg anymore, just the engine itself doesn't run

**Comment by TheMispeled** [comment]
Hi ,i have the same problem, it might be the ignition. Other people dont have this problem strangely.

**Comment by TristonStuart** [comment]
Related To: https://github.com/ange-yaghi/engine-sim/issues/31#issue-1336038144

Many people have reported poor performance when using more cylinders, although I believe it may be a bug due to the CPU cores not being fully loaded (or even 1 since it uses a single core for the simulator processing).

**Comment by ange-yaghi** [comment]
I'll look into it, this might have been fixed in newer versions

**Comment by TheMispeled** [comment]
I've cheked and only 1 core is under heavy load and another 1 is under little load

**Comment by ange-yaghi** [comment]
That's not too surprising, the mechanical components run in 1 thread and the audio runs in another. For multi-cylinder engines it would make sense for one thread to be more stressed than the other.

**Comment by TristonStuart** [comment]
> I'll look into it, this might have been fixed in newer versions

Had the same issues with the V8 on the GitHub compiled release, but the discord pre-compiled release runs just fine for me. The discord release has the frequency set to 5k but even setting the GitHub version to 5k the engine doesn't run.

**Comment by fatalerrorcoded** [comment]
It looks like the crankshaft TDCs are defined as -315° (`constants.pi / 4 - 2 * constants.pi`), which I assume works with the Discord release. However, in the GitHub release, it turns out the engines only work if the TDC is defined as -45° (`-45 * units.deg` for example), 90°/270° offset from the original TDC

**Comment by ange-yaghi** [comment]
This should be fixed now.

**Comment by probrogamer52** [comment]
im getting the same thing happening but with the 2jz ange made and i cant get past the unidentified node type

**Comment by probrogamer52** [comment]
nvm its every engine
