### ISSUE TITLE
how to change piston shape

### ISSUE THREAD

**Issue by Abdullah-Ajeebi** [ange-yaghi/engine-sim#341]
like a bump, for example

**Comment by Magicoo51889** [comment]
You don't really need to be able to change the shape, as long as you code the engine to act like an engine with oval pistons/cylinders. The sim doesn't know the shape of the pistons/cylinders as far as I'm aware

**Comment by Abdullah-Ajeebi** [comment]
i meant like this [one](https://www.youtube.com/watch?v=1dlPJyASNt0)
