### ISSUE TITLE
PLEASE FIX NO ENGINE BUG!!!😪😪

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#348]

**Comment by Peugeot205GTI** [comment]
again, stop with all caps 
ange-yaghi said that this free version will no longer be mainained he is now focusing on a 3D version with no bugs, better audio and in-game engine builder and selector

**Comment by jim4800frank** [comment]
> again, stop with all caps ange-yaghi said that this free version will no longer be mainained he is now focusing on a 3D version with no bugs, better audio and in-game engine builder and selector

Can't wait!!!

**Comment by ange-yaghi** [comment]
Issue not clear.
