### ISSUE TITLE
WHY IS THIS SO UNFUNCTIONAL!!!!😪😪😪🤬🤬

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#349]
BECAUSE YOU GO TO NOTEPAD > RUN BUTTON THERE'S A KICKOUT NOR NO ENGINE BUG!!!!😪😪

**Comment by Peugeot205GTI** [comment]
bro can you stop using ALL CAPS

**Comment by ange-yaghi** [comment]
Bruh
