### ISSUE TITLE
The sim is incomplete

### ISSUE THREAD

**Issue by TheMispeled** [ange-yaghi/engine-sim#35]
I love this sim!
But to change the engine, we need to edit some files.
You know the deal.🤓
It would be more intuitive to have a menu to change engines.

Also its too hard to edit/make the engines!!!!!
It would be cool to have a visual editor like Automation.
Yeah.🤓

If someone could do it, it would be simulation-changing

**Comment by Jckf** [comment]
Engine builder GUI https://github.com/ange-yaghi/engine-sim/issues/18

**Comment by ange-yaghi** [comment]
Closing as duplicate
