### ISSUE TITLE
lunch the game

### ISSUE THREAD

**Issue by jneighnb** [ange-yaghi/engine-sim#354]
im confused i cant fined the bin folder

**Comment by Abdullah-Ajeebi** [comment]
go to the releases page at [here](https://github.com/ange-yaghi/engine-sim/releases)

**Comment by TheEvilSkeletor** [comment]
please do not eat the simulator. it is software and thus inedible.

**Comment by Abdullah-Ajeebi** [comment]
i just noticed that "lunch", should've been "launch"

**Comment by Jckf** [comment]
No feedback from issue owner in over 2 weeks. Closing.
