### ISSUE TITLE
3D version when?

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#358]

**Comment by Abdullah-Ajeebi** [comment]
2026

**Comment by jim4800frank** [comment]
> 2026

LIE LIE LIE LIE LIE LIE!!!!🤬🤬🤬😪😪

**Comment by Abdullah-Ajeebi** [comment]
just an estimate, also can you press caps lock..... **again**

**Comment by jim4800frank** [comment]
> just an estimate, also can you press caps lock..... **again**

SORRY FOR STUPID JOKES!!!!!!😪😪😪

**Comment by Abdullah-Ajeebi** [comment]
no u
