### ISSUE TITLE
Sim Unresponsive on Remote Desktop

### ISSUE THREAD

**Issue by TheEvilSkeletor** [ange-yaghi/engine-sim#362]
I've recently noticed an issue where the program is unresponsive to inputs from a remote desktop. In my case, I tried opening the sim on my desktop, which was being controlled by my laptop over Parsec. The sim will open per usual, but nothing from the remote end (including the use of the Windows on-screen keyboard) will result in anything.
Given how I wrote all of this over the same remote desktop, it seems as though everything is functioning normally.

By no means is this a major issue, just a weird one.

**Comment by Abdullah-Ajeebi** [comment]
#99

**Comment by Jckf** [comment]
Closing as duplicate.
