### ISSUE TITLE
Changing engine.

### ISSUE THREAD

**Issue by googleyroll** [ange-yaghi/engine-sim#364]
Does anybody know how to change the engine?

**Comment by Golevka2001** [comment]
Hi! I wrote a tool helping switch engine more easily. Maybe this will help you.

<https://github.com/Golevka2001/Config-Loader-for-Engine-Sim>

**Comment by Abdullah-Ajeebi** [comment]
i made this pr in changing the engine from `"01_subaru_ej25_eh"` to `"02_subaru_ej25_uh"`
