### ISSUE TITLE
I wrote a tool helping switch engine more easily

### ISSUE THREAD

**Issue by Golevka2001** [ange-yaghi/engine-sim#366]
Hi! I wrote a tool helping switch engine more easily. Maybe this will help you.

https://github.com/Golevka2001/Config-Loader-for-Engine-Sim

![main_window_1](https://user-images.githubusercontent.com/101185502/197800456-633d4d5c-d6ad-4128-ba50-74cf7d5c7df1.png)

**Comment by Sukooo** [comment]
Good job!

**Comment by jim4800frank** [comment]
Nooooo fix this!!😪
![Screenshot (1087)](https://user-images.githubusercontent.com/110838600/197829441-1a04241b-d740-4773-b74f-3a46f67419ce.png)

**Comment by MilkMan1093** [comment]
_My god, dude._ You put the darn folder in the root directory of engine sim after you unzip it! -_-

**Comment by Golevka2001** [comment]
> Nooooo fix this!!😪 ![Screenshot (1087)](https://user-images.githubusercontent.com/110838600/197829441-1a04241b-d740-4773-b74f-3a46f67419ce.png)

😂Sorry dude, forgot to mention, the folder should be in the same path as ```engine-sim-app.exe```

Youo can get more infomation [here](https://github.com/Golevka2001/Config-Loader-for-Engine-Sim)

![location](https://user-images.githubusercontent.com/101185502/198204438-af82751f-910a-407e-b0e0-3392ec36c329.png)

**Comment by jim4800frank** [comment]
> > Nooooo fix this!!😪 ![Screenshot (1087)](https://user-images.githubusercontent.com/110838600/197829441-1a04241b-d740-4773-b74f-3a46f67419ce.png)
> 
> 😂Sorry dude, forgot to mention, the folder should be in the same path as `engine-sim-app.exe`
> 
> Youo can get more infomation [here](https://github.com/Golevka2001/Config-Loader-for-Engine-Sim)
> 
> ![location](https://user-images.githubusercontent.com/101185502/198204438-af82751f-910a-407e-b0e0-3392ec36c329.png)

Lol "Youo"

**Comment by Jckf** [comment]
"Issues" are not for advertising your own projects.
