### ISSUE TITLE
I wish!!😪

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#367]
![Screenshot (1090)](https://user-images.githubusercontent.com/110838600/198066829-99ce594d-1e47-4ecf-9898-1590015c08da.png)

**Comment by ange-yaghi** [comment]
It seems like a lot of people have consistent complaints about your behavior. Maybe it's time to accept the fact that this is a pattern and adjust your behavior accordingly. You've opened at least 20 issues on this GitHub repo, easily more than any other person. Do you think this is normal? Please, think about what you're doing and how you're coming across to people. This very issue that you've opened is completely off-topic and irrelevant for this repo. If you continue behaving this way, you will be banned and thus unable to open any more issues. This is a warning.

**Comment by CNSabata** [comment]
Just wanna let you know that this individual is very non-representative of the rest of your audience. I believe you also have a less voiced fanbase that is very fond of the work you provide.
Thank you for your hard work, you are doing motorheads a blessing with your application @ange-yaghi.
If you so decide to purge his issues / ban him from posting answers on the repo, I'm sure many of us won't mind at all.
