### ISSUE TITLE
I want him to keep working on Advanced Vehicle Editor!!😪

### ISSUE THREAD

**Issue by jim4800frank** [ange-yaghi/engine-sim#368]
![Screenshot (1091)](https://user-images.githubusercontent.com/110838600/198068338-d1dae2f3-9bc0-4a8e-83b3-3779e068278b.png)

**Comment by Abdullah-Ajeebi** [comment]
this is motorsim right?

or design 3d models by yourself and see how that goes!

**Comment by jim4800frank** [comment]
I'm sorry I can't!!😪

**Comment by Abdullah-Ajeebi** [comment]
**learn**
