### ISSUE TITLE
is there any demo for 3d sim?

### ISSUE THREAD

**Issue by quinnzaballa** [ange-yaghi/engine-sim#370]
I would try an demo and buy it if its good, anyways this jim4800frank is flooding the issues. if you read this. why not join the discord and tell any off-topic things you wanna post. probably you'll met new friends there.

**Comment by quinnzaballa** [comment]
also can i possibly take an whole info of specific error in error logs it makes me rage quit in my engine

**Comment by Abdullah-Ajeebi** [comment]
look here [Wiki:How to read the error log](https://github.com/ange-yaghi/engine-sim/wiki/How-to-read-the-error-log)

**Comment by quinnzaballa** [comment]
> look here [Wiki:How to read the error log](https://github.com/ange-yaghi/engine-sim/wiki/How-to-read-the-error-log)

thanks i have never seen that link or faq.
