### ISSUE TITLE
Game is glitched 

### ISSUE THREAD

**Issue by rskimhnfrg** [ange-yaghi/engine-sim#380]
I got the game yesterday the newest version and as soon as I opened the app the needles were just viberating like the RPM and stuff like that with the engine off so I started the engine and my speakers just pop please help.

**Comment by MilkMan1093** [comment]
Plug in a computer mouse.
Open Engine Simulator.
Hold down N on your keyboard and scroll down using the mouse.
Do this until the game runs smoothly.

**Comment by rskimhnfrg** [comment]
Hi, I tried this and didn’t work.On Nov 8, 2022, at 7:48 AM, MilkMan1093 ***@***.***> wrote:﻿
Plug in a computer mouse.
Open Engine Simulator.
Hold down N on your keyboard and scroll down using the mouse.
Do this until the game runs smoothly.

**Comment by Jckf** [comment]
Read the FAQ. If reducing simulation frequency doesn't help, then your computer is most likely not powerful enough.
