### ISSUE TITLE
Cannot launch application

### ISSUE THREAD

**Issue by icantreadmycode** [ange-yaghi/engine-sim#386]
after downloading and unziping, i recieved an error that `d3dx11_43.dll` was not found.
 
![image](https://user-images.githubusercontent.com/114925991/202518904-82ba25be-2ee9-4073-a57b-dd27e9c26506.png)

```
OS: Windows: 11 Pro 2262
engine-sim: 0.1.11a & 0.1.10a
```
i have tried reinstalling, and downgrading the program & restarting my laptop

**Comment by MilkMan1093** [comment]
Check [this article](https://github.com/ange-yaghi/engine-sim/wiki/Missing-DLL-files)
