### ISSUE TITLE
Opening and closing immidiately

### ISSUE THREAD

**Issue by ZxBeta** [ange-yaghi/engine-sim#388]
![Screenshot_20221121_124826](https://user-images.githubusercontent.com/115987766/202988461-6758a415-4b87-4f86-bbb5-60c34a8406e7.png)

OS : win 11 22H2

as soon as i click on it and say yes to admin panel the app will open on black screen for 0.5 sec and then it will close immideately

sim-enigne verson : 0.1.11a
exe file that i'm trying to run : in bin folder "engine-sim-app" {just in case i don't know where the real exe file is}

**Comment by brunoman4006** [comment]
I have the same case, but instead being black it goes white, and after a few seconds it closes

(i had an error about a d3dx11_43.dll before that i fixed adding the file inside the bin folder)

**Comment by jedrek2206** [comment]
> There is already a discussion in #27 but it has been a long time from the last response. The problem with the most , including me , is when you are using an integrated graphics card. But I hope this will be resolved as soon as possible

Hi,

I will write here to not steal #27 at this moment. Have the same problem of white screen for 2 sec when starting engine-sim-app, and then it crash without any information in error log. Fresh download of 0.1.11a.
BUT
I don't use integrated graphics.
My setup:
- i3-4160 3.6 GHz
- 16 GB RAM
- GTX 1060 3gb
- Win 10 Pro, 64-bit
I have tried almost every mentioned solution but none of them fixed the problem :/ 
All .dll's are there, no errors, just doesn't start. Maybe do You have any idea?
App itself looks amazing and I desperately want to play with #197 

BR

**Comment by kunimei** [comment]
thankyou
