### ISSUE TITLE
Not able to change engine.

### ISSUE THREAD

**Issue by ninjamyles** [ange-yaghi/engine-sim#389]
Please help, I am not able to change engines.
Version is V0.1.11A
Error Code: main(7): error R0010: Undefined node type
![2022-11-23](https://user-images.githubusercontent.com/118873994/203473253-38867fdf-38c7-4f00-ba95-0b01294ef20a.png)

**Comment by MilkMan1093** [comment]
Trying to change engines manually is quite the difficult task. Use [Engine Hoist.](https://github.com/sta0003/EngineHoist/releases/tag/V1.4.0) It is very easy to use.

**Comment by kunimei** [comment]
you are very good

**Comment by Jckf** [comment]
Read the FAQ.
