### ISSUE TITLE
Opening other engines??

### ISSUE THREAD

**Issue by pauel3312** [ange-yaghi/engine-sim#399]
I have downloaded the app and successfully ran the default engine simulation (engines/atg-video-2/01_subaru_ej25_eh.mr), but as soon as I want to change the used engine (by litterally copy-pasting the code of the question about how to change the unit system (which also selects the audi i5 engine or just importing an other .mr and using set_engine to select it), it reports no engine. Any fix?

**Comment by Abdullah-Ajeebi** [comment]
two things

1. send screenshot
2. send main.mr

**Comment by pauel3312** [comment]
Here is an example of main.mr I have been using and a screen of the app with it. I have noticed something odd: yesterday, I forced my PC in long sleep (IDK if that is the real name I'm french), and when I came back to it, my edited main.mr worked but only with the engine I had set before shutting it down. 
[main.mr.txt](https://github.com/ange-yaghi/engine-sim/files/10235779/main.mr.txt)
![image](https://user-images.githubusercontent.com/84579492/207828679-0861aadb-bcef-49bf-a033-26f527bf3d05.png)

**Comment by Abdullah-Ajeebi** [comment]
you used `main()` and `set_engine(audi_i5_2_2L())`,
those are not meant to be mixed together because `main()` sets the car and tranmission and engine TOGETHER,
and `set_engine(audi_i5_2_2L())` sets ONLY the engine,
do it would look like this 
[main.mr.txt (edited)](https://github.com/ange-yaghi/engine-sim/files/10237402/main.mr.txt)

**Comment by pauel3312** [comment]
OK it works now, thanks for your help!

**Comment by Jckf** [comment]
> `main()` sets the car and tranmission and engine TOGETHER

This is not true. `main()` does whatever the author has decided that it should do. It could for instance change the units used in the sim.
