### ISSUE TITLE
Application captures keystrokes even when not focused

### ISSUE THREAD

**Issue by NexusXe** [ange-yaghi/engine-sim#4]
Click off the application and start typing. It captures these inputs as actual input, instead of ignoring them. Kinda scary that it's always capturing keystrokes regardless... :/

**Comment by 13Stewartc** [comment]
This issue exists for me as well.

**Comment by 14rss** [comment]
Same issue. Very annoying.

**Comment by ange-yaghi** [comment]
Should be fixed now

**Comment by regtable** [comment]
only fixed if self building? as i see no release recent.
