### ISSUE TITLE
Error with CMake: Could NOT find FLEX

### ISSUE THREAD

**Issue by Devarite** [ange-yaghi/engine-sim#40]
When I try to build I get the error: CMake Error: Could NOT find FLEX
Where do I get/build flex?

I have all required dependencies installed and added to PATH

Full error message from Visual Studio:
```
CMake Error at C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230
 (message): Could NOT find FLEX (missing: FLEX_EXECUTABLE)
```

I am using Visual Studio 2022 on Windows 10.

**Comment by BuiltWithBytes** [comment]
Try this
