### ISSUE TITLE
Continuously Crashing

### ISSUE THREAD

**Issue by ThunderDZNGITH** [ange-yaghi/engine-sim#404]
Hi, it keep crashing every time i try to open the .exe file

I am on a fresh windows install with absolutely nothingon it, i installed directX and vulkanRT but it keep crashing every time.

And the error_log is blank so i can't know what is happening

**Comment by Abdullah-Ajeebi** [comment]
give me the install to see if it works for me.

**Comment by jansaternus** [comment]
> Hi, it keep crashing every time i try to open the .exe file
> 
> I am on a fresh windows install with absolutely nothingon it, i installed directX and vulkanRT but it keep crashing every time.
> 
> And the error_log is blank so i can't know what is happening

Maybe your hardware isn't good enough for this?

**Comment by ThunderDZNGITH** [comment]
Hi, sorry for the late reply.

In fact it was a problem of graphics card driver, I'm on an old lenovo g550 and the last drivers are not available for windows 10, I went back to windows 7 (yes yes I know it's hard) and it works well, this said it would be cool to have a compiled version for linux (debian/unbuntu whatever)
