### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by UnBeatWaterGH** [ange-yaghi/engine-sim#411]
The engine-sim-app.exe dosen't work. I try to double-click it but it crashes. Info below.

**Comment by DDev247** [comment]
Are you running it on macOS?
If you do can you also send the device you're using and the version of macOS?

If you aren't (Linux then) you need to install wine.
Go to the wineHQ website for instructions.

**Comment by UnBeatWaterGH** [comment]
I'm on MacOS 13.0.1. A 2020 Mac mini with an M1 processor, 16 GB of ram.

Using CrossoverFOSS/CrossoverWine to get a copy of Wine.

However, when I try to run the engine-sim-app.exe it gives me an error: "
**The program engine-sim-app.exe has encountered a serious problem and needs to close. We are sorry for the inconvenience**
This can be caused by a problem in the program or a deficiency in Wine.

[Show Details] [Close]
"

**Comment by DDev247** [comment]
So you are using Wine right? Okay. One thing I know is Wine on macOS with ES always gives some sort of memory error.
And since you're on M1 you will probably not have much luck on that. You can still try compiling the source somehow but I'm not going to go into too much depth on how to do this.

**Comment by UnBeatWaterGH** [comment]
I can compile it don't worry. Just that i don't want to right now.
