### ISSUE TITLE
While building the project in Visual Studio 2022 I keep getting the error "identifier 'm_antialiasingFilters' is undefined".

### ISSUE THREAD

**Issue by lokitkhemka** [ange-yaghi/engine-sim#413]
I am getting the error while building the project "engine-sim-app" in Visual Studio 2022 saying
"identifier "m_antialiasingFilters" is undefined" at "D:\engine-sim\src\piston_engine_simulator.cpp" file at line 36.

Any help in solving this issue is appreciated.

**Comment by ange-yaghi** [comment]
That member doesn't exist, so you can delete the line that uses it. This only happens when building in Debug mode which I rarely if-ever do.
