### ISSUE TITLE
Torque caps out at 10000 lb-ft in dynamometer

### ISSUE THREAD

**Issue by PajerLevi** [ange-yaghi/engine-sim#429]
I am making a very high performance engine (8000 hp<) , and when I try to measure it's power and torque, then when the torque reaches 10000 lb-ft, is acts like a clutch with that as it's maximum torque, and continues slipping until it goes below 10000 lb-ft. Engine:
[w8.zip](https://github.com/ange-yaghi/engine-sim/files/11708023/w8.zip)

**Comment by Abdullah-Ajeebi** [comment]
Thats a problem you can fix by editing the source

في الجمعة، ٩ يونيو ٢٠٢٣, ٦:٥٣ م PajerLevi ***@***.***> كتب:

**Comment by PajerLevi** [comment]
Where do I edit the source?

**Comment by Abdullah-Ajeebi** [comment]
On this repository

في السبت، ١٠ يونيو ٢٠٢٣, ١٢:٥٦ م PajerLevi ***@***.***> كتب:

**Comment by Titanic4** [comment]
https://github.com/ange-yaghi/engine-sim/blob/85f7c3b959a908ed5232ede4f1a4ac7eafe6b630/src/dynamometer.cpp#L11
This line in dynamometer.cpp file sets the maximum torque in ft-lb. Change the first parameter of the function to the desired limit before recompiling.

**Comment by PajerLevi** [comment]
Thank you Titanic4!
