### ISSUE TITLE
Issue with Conrods on custom engine

### ISSUE THREAD

**Issue by RealSourceOfficial** [ange-yaghi/engine-sim#431]
Hello, I was recently working on my 7M-GE replica, and upon the first time loading it the engine seems to instantly disappear. Upon reducing the sim speed, I found that the conrods started shaking violently before being promptly deleted (along with the rest of the engine).

[Engine configuration file](https://github.com/ange-yaghi/engine-sim/files/12010317/7m-ge.txt)

https://github.com/ange-yaghi/engine-sim/assets/65256422/15ef3f04-bc91-41e0-8879-3b1d73f37eba

**Comment by RealSourceOfficial** [comment]
For anyone wondering why some of the config was left alone/appears in other files while the rest is heavily edited/detailed: I'm still working on modeling the engine. There's very little documentation on the 7M-GE, and it already took me 5+ hours to write what I have, so stuff like the intake/exhaust isn't my biggest concern. I'm more concerned about the accuracy.

**Comment by Abdullah-Ajeebi** [comment]
It looks like the moment of inertia of the connecting rod is too low. You can fix this by multiplying the moment of inertia by 10, So it would look from
`    connecting_rod_parameters cr_params(
mass: 1723.651 * units.g,
moment_of_inertia: 0.00002,
center_of_mass: 0.0,
length: (302.02 - 0.5 * 91 - 33.0) * units.mm
 )`
To
`connecting_rod_parameters cr_params(
mass: 1723.651 * units.g,
moment_of_inertia: 0.0002,
center_of_mass: 0.0,
length: (302.02 - 0.5 * 91 - 33.0) * units.mm
)`

Also fix your rod journal angles and make it like
`
rod_journal rj0(angle: (0.0 / 6.0) * 360 * units.deg)
rod_journal rj1(angle: (2.0 / 6.0) * 360 * units.deg)
rod_journal rj2(angle: (4.0 / 6.0) * 360 * units.deg)
rod_journal rj3(angle: (4.0 / 6.0) * 360 * units.deg)
rod_journal rj4(angle: (2.0 / 6.0) * 360 * units.deg)
rod_journal rj5(angle: (0.0 / 6.0) * 360 * units.deg)`

Overall, here is the fixed version of the [file](https://github.com/ange-yaghi/engine-sim/files/12023353/7m-ge.txt)

**Comment by RealSourceOfficial** [comment]
Thanks! The engine seems to be working again, now I can get back to work!
