### ISSUE TITLE
Error: "The code execution cannot proceed because vulkan-1.dll was not found."

### ISSUE THREAD

**Issue by AlphaComputer7** [ange-yaghi/engine-sim#45]
I don't know why this is happening, I tried extracting everything but still nothing. Here is the full error code.
![image](https://user-images.githubusercontent.com/79499360/184360965-c4f739d7-dfbd-4d7a-b0fb-4d9a635aa801.png)

**Comment by Sleff1** [comment]
You need to install it manually I had the same error and installed it from link under [https://youtu.be/kQH_PUFTTpw](this video) and it works

**Comment by AlphaComputer7** [comment]
> You need to install it manually I had the same error and installed it from link under [this video](https://youtu.be/kQH_PUFTTpw) and it works

It works! But now it crashes after opening

**Comment by Sleff1** [comment]
Actually a lot of people has this issue including me and I already created issue about this

**Comment by NotoriusNeo** [comment]
You have to install this! 

https://developer.nvidia.com/vulkan-driver
