### ISSUE TITLE
Kohler_ch750 Crashes immediately after opening 

### ISSUE THREAD

**Issue by Wolf52804** [ange-yaghi/engine-sim#58]
Engine crashes immediately after opening on Build_1_4_a

**Comment by TheMispeled** [comment]
yea same, it loads, we can see it but it crashes

**Comment by Kevin15673** [comment]
I have the same issue, error.log doesn't show any errors and afaik there aren't any other log files

**Comment by Kevin15673** [comment]
It's because the directories for the audio files are wrong

**Comment by 14rss** [comment]
> I have the same issue, error.log doesn't show any errors and afaik there aren't any other log files

There aren't any errors shown in the log from my experience, yeah.
Is it really the audio directories? Out of curiosity, how could that be the issue?
Don't they all use the same audio files?
If you fixed it, please upload the changes. I'd love to test it out.

**Comment by Kevin15673** [comment]
> 

It's line 76 of the .mr file, by default it's "impulse_response ir0(filename: "../../smooth_39.wav", volume: 0.001)" but it needs to be "impulse_response ir0(filename: "../../sound-library/smooth/smooth_39.wav", volume: 0.001)"

**Comment by 14rss** [comment]
> > 
> 
> It's line 76 of the .mr file, by default it's "impulse_response ir0(filename: "../../smooth_39.wav", volume: 0.001)" but it needs to be "impulse_response ir0(filename: "../../sound-library/smooth/smooth_39.wav", volume: 0.001)"

Thank you!!
That did it (◕‿◕✿)

**Comment by ange-yaghi** [comment]
Should be fixed in next release
