### ISSUE TITLE
High pitch buzz upon executing application

### ISSUE THREAD

**Issue by 14rss** [ange-yaghi/engine-sim#6]
High pitch sound only lasts maybe half a second. Not exactly an issue but it is odd.
I also can't seem to keep the engine running when switching into gear - yes, I'm using clutch too.
Otherwise, this application works very very well. What an amazing concept.

**Comment by 14rss** [comment]
I've noticed it also occurs when maximizing the window for the first time.

**Comment by Chalcedonity** [comment]
Can you help me? I really have no idea how to run the code - there are so many things that I have no idea what to do. I tried looking it up but that just leads me down more rabbit holes. Seeing as you have it running, could you explain how you did it, eg use OBS to go through what you did? I know others are having the same problem. If not, do you think that someone will make the files all executable under an .exe in the near future?

**Comment by 14rss** [comment]
> Can you help me? I really have no idea how to run the code - there are so many things that I have no idea what to do. I tried looking it up but that just leads me down more rabbit holes. Seeing as you have it running, could you explain how you did it, eg use OBS to go through what you did? I know others are having the same problem. If not, do you think that someone will make the files all executable under an .exe in the near future?

Sure, the executable is in the `bin` directory within the `build_1_3a` folder which can be downloaded [here](https://github.com/ange-yaghi/engine-sim/releases/download/v0.1.3a/build_1_3a.zip)
the executable is `engine-sim-app`.
Let me know if you need any more help.

**Comment by Chalcedonity** [comment]
> > Can you help me? I really have no idea how to run the code - there are so many things that I have no idea what to do. I tried looking it up but that just leads me down more rabbit holes. Seeing as you have it running, could you explain how you did it, eg use OBS to go through what you did? I know others are having the same problem. If not, do you think that someone will make the files all executable under an .exe in the near future?
> 
> Sure, no building is required. The executable is in the `bin` directory within the `build_1_3a` folder which can be downloaded [here](https://github.com/ange-yaghi/engine-sim/releases/download/v0.1.3a/build_1_3a.zip) the executable is `engine-sim-app`. Let me know if you need any more help.

Thank you so much. Did not realise this. And if I was to create a new engine, like a V10 say, is this very difficult? Thanks

**Comment by 14rss** [comment]
> > > Can you help me? I really have no idea how to run the code - there are so many things that I have no idea what to do. I tried looking it up but that just leads me down more rabbit holes. Seeing as you have it running, could you explain how you did it, eg use OBS to go through what you did? I know others are having the same problem. If not, do you think that someone will make the files all executable under an .exe in the near future?
> 
> > 
> 
> > Sure, no building is required. The executable is in the `bin` directory within the `build_1_3a` folder which can be downloaded [here](https://github.com/ange-yaghi/engine-sim/releases/download/v0.1.3a/build_1_3a.zip) the executable is `engine-sim-app`. Let me know if you need any more help.
> 
> 
> 
> Thank you so much. Did not realise this. And if I was to create a new engine, like a V10 say, is this very difficult? Thanks

That, I'm not sure about. I think with some time, there will probably be a better version of this and hopefully a workshop. That would be awesome, honestly. For now though, this is only a demo from what I know and the idea will probably be expanded on based on how popular this has become. Sorry I can't give a real answer though! >.>

**Comment by Chalcedonity** [comment]
Yeah that’s totally fine. As a demo I’m more than happy and sure it will be added on to like you said. I can’t wait to have other engine configurations as I’m a car and bike nut - like an in-line 3 or in-line 4 from motorcycles. Do you happen to know how to load the V8 because when launching the application it is the Kohler by default. Thanks

**Comment by 14rss** [comment]
> Yeah that’s totally fine. As a demo I’m more than happy and sure it will be added on to like you said. I can’t wait to have other engine configurations as I’m a car and bike nut - like an in-line 3 or in-line 4 from motorcycles. Do you happen to know how to load the V8 because when launching the application it is the Kohler by default. Thanks

Honestly, I was looking around for a way to load the V8 as well. I still can't find any answers but if I do, I'll let you know. I'm thinking that it isn't programmed into the app yet because I only saw 1 engine in the code... >_>
Really wish I knew.
I tried every button on my keyboard but couldn't find anything.

**Comment by Chalcedonity** [comment]
Sure thing. Best case scenario is it keeps getting updated with an engine builder :D

**Comment by 14rss** [comment]
> Sure thing. Best case scenario is it keeps getting updated with an engine builder :D

I have high hopes!（＾ω＾）

**Comment by ange-yaghi** [comment]
A bit of random noise plays when the simulation first opens which is not intentional. I'll see about fixing it.

**Comment by DDev247** [comment]
> A bit of random noise plays when the simulation first opens which is not intentional. I'll see about fixing it.

Also for me with my lawnmower engine it makes high pitch noises when idling

**Comment by ange-yaghi** [comment]
Should be fixed now
