### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by Colrover546** [ange-yaghi/engine-sim#61]
Im having great performance issues and i don't know why exactly (probably cuz PC)

I would like to know the minimum specs for running the simulation OK, if those are available, please and thanks

**Comment by Colrover546** [comment]
What i mean by minimum specs is what FPS people have gotten from a mid to low end PC

**Comment by DDev247** [comment]
minimum specs vary from engine to engine so that's not possible

**Comment by Colrover546** [comment]
> minimum specs vary from engine to engine so that's not possible

Ok, but how do i change engines???

**Comment by 14rss** [comment]
> > minimum specs vary from engine to engine so that's not possible
> 
> Ok, but how do i change engines???

There should be another issue that covers how to do this, but the only thing you need to change is the values in main...
`assets > engines > main.mr`
From there, you edit the parameters to what each engine is.
So, if you wanted the Audi engine (for example), your `main.mr` file will read as:

`import "engine_sim.mr"
import "part-library/part_library.mr"
import "engines/audi/i5.mr"

set_engine(
engine: audi_i5_2_2L()
)`

It's sort of confusing though, since some engines may have different public nodes than their actual engine .mr file (which can be found within `engines > [name of engine folder] > [enginename].mr`
The audi engine is the only engine like that though, IIRC.
Sorry for the wall of text, hope this helps (✿╹◡╹)

**Comment by Colrover546** [comment]
> > > minimum specs vary from engine to engine so that's not possible
> > 
> > 
> > Ok, but how do i change engines???
> 
> There should be another issue that covers how to do this, but the only thing you need to change is the values in main... `assets > engines > main.mr` From there, you edit the parameters to what each engine is. So, if you wanted the Audi engine (for example), your `main.mr` file will read as:
> 
> `import "engine_sim.mr" import "part-library/part_library.mr" import "engines/audi/i5.mr"
> 
> set_engine( engine: audi_i5_2_2L() )`
> 
> It's sort of confusing though, since some engines may have different public nodes than their actual engine .mr file (which can be found within `engines > [name of engine folder] > [enginename].mr` The audi engine is the only engine like that though, IIRC. Sorry for the wall of text, hope this helps (✿╹◡╹)

Thank you! i really appreciate it!

**Comment by 14rss** [comment]
> > > > minimum specs vary from engine to engine so that's not possible
> > > 
> > > 
> > > Ok, but how do i change engines???
> > 
> > 
> > There should be another issue that covers how to do this, but the only thing you need to change is the values in main... `assets > engines > main.mr` From there, you edit the parameters to what each engine is. So, if you wanted the Audi engine (for example), your `main.mr` file will read as:
> > `import "engine_sim.mr" import "part-library/part_library.mr" import "engines/audi/i5.mr"
> > set_engine( engine: audi_i5_2_2L() )`
> > It's sort of confusing though, since some engines may have different public nodes than their actual engine .mr file (which can be found within `engines > [name of engine folder] > [enginename].mr` The audi engine is the only engine like that though, IIRC. Sorry for the wall of text, hope this helps (✿╹◡╹)
> 
> Thank you! i really appreciate it!

Happy to help! (＾▽＾)
I hope you were able to get it working properly.

**Comment by Colrover546** [comment]
> 14rss

Yea im fiddling with it rn and im going somewhere :D

**Comment by 14rss** [comment]
> > 14rss
> 
> Yea im fiddling with it rn and im going somewhere :D

Oooh, awesome! ｡^‿^｡
In regards to performance, keep in mind that you can change the simulation frequency by holding `N` and moving the scroll wheel (lower, the faster).
I've heard that adding exhaust pipes can also help with performance...
but I'm not 100% sure since I haven't actually made an engine ´･ᴗ･`

**Comment by Colrover546** [comment]
> > > 14rss
> > 
> > 
> > Yea im fiddling with it rn and im going somewhere :D
> 
> Oooh, awesome! ｡^‿^｡ In regards to performance, keep in mind that you can change the simulation frequency by holding `N` and moving the scroll wheel (lower, the faster). I've heard that adding exhaust pipes can also help with performance... but I'm not 100% sure since I haven't actually made an engine ´･ᴗ･`

Yea so i managed to get 2 engines that work OK but the sound is kinda bugged ima try that

**Comment by 14rss** [comment]
> > > > 14rss
> > > 
> > > 
> > > Yea im fiddling with it rn and im going somewhere :D
> > 
> > 
> > Oooh, awesome! ｡^‿^｡ In regards to performance, keep in mind that you can change the simulation frequency by holding `N` and moving the scroll wheel (lower, the faster). I've heard that adding exhaust pipes can also help with performance... but I'm not 100% sure since I haven't actually made an engine ´･ᴗ･`
> 
> Yea so i managed to get 2 engines that work OK but the sound is kinda bugged ima try that

Yup, crackling audio is most likely caused by latency! Simulation frequency should help (✿╹◡╹)

**Comment by Colrover546** [comment]
Update: sounds are bugged! send help (i rev the engine and i hear it idling)

**Comment by Colrover546** [comment]
> Update: sounds are bugged! send help (i rev the engine and i hear it idling)

Also im getting to crash by revving it LOL

**Comment by 14rss** [comment]
> > Update: sounds are bugged! send help (i rev the engine and i hear it idling)
> 
> 
> 
> Also im getting to crash by revving it LOL

What's your engine's specs? Have you tried adding exhaust pipes? (@_@) Hmmmmm...

**Comment by Colrover546** [comment]
How do i add exhaust pipes???

> > > Update: sounds are bugged! send help (i rev the engine and i hear it idling)
> > 
> > 
> > Also im getting to crash by revving it LOL
> 
> What's your engine's specs? Have you tried adding exhaust pipes? (@_@) Hmmmmm...

How do i add exhaust pipes?
