### ISSUE TITLE
How do you switch to a different Engine?

### ISSUE THREAD

**Issue by Honestlypotato** [ange-yaghi/engine-sim#62]
I just downloaded this, and I have to say this is amazing and thank you for letting the public use this for free, but I have a question on how to change which engine you are simulating? Is it something in the files, is there a key or set of key that a press? Once again this is amazing.

**Comment by Honestlypotato** [comment]
As well as how do you change the config of engines because I really want to just mess around with intakes and what not because it just seems really fun.

**Comment by TheMispeled** [comment]
go into assets folder then open main.mr : you will see this: 
import "engine_sim.mr"
import "part-library/part_library.mr"
import "engines/bmw/M52B28.mr"

set_engine(
    engine: M52B28()
)

Just change it to like : 
import "engine_sim.mr"
import "part-library/part_library.mr"
import "engines/chevrolet/chev_truck_454.mr"

set_engine(
    engine: chev_truck_454()
)

for the v8 engine

**Comment by Honestlypotato** [comment]
Thanks for the help
