### ISSUE TITLE
Cannot load the audi engine

### ISSUE THREAD

**Issue by TheMispeled** [ange-yaghi/engine-sim#64]
put this into main.mr file:
import "engine_sim.mr"
import "part-library/part_library.mr"
import "engines/audi/i5.mr"

set_engine(
    engine: i5()
)

It crashes

**Comment by DarshK35** [comment]
The set engine is incorrect. It should be
```
set_engine(
engine: audi_i5_2_2L()
)
```

**Comment by ange-yaghi** [comment]
Closing as "no issue".
