### ISSUE TITLE
The code execution cannot proceed because d3dx11_43.dll was not found.

### ISSUE THREAD

**Issue by MilkMan1093** [ange-yaghi/engine-sim#65]
The app will not start because a dll file is missing 
![image](https://user-images.githubusercontent.com/88229702/184501639-9df2d9bd-a4ff-48a9-9b13-da6c6e500790.png)
Help.

**Comment by MilkMan1093** [comment]
Okay, I got rid of that issue, but now the app opens with a white screen and then crashes. HELP.

**Comment by TheMispeled** [comment]
Download it, try replacing .mov to .dll and name it d3dx11_43.it shoul maybe fix it
https://user-images.githubusercontent.com/111089725/184501775-90d648ee-e892-40c8-8e3b-2a2423b56ae0.mov

**Comment by MilkMan1093** [comment]
> Download it, try replacing .mov to .dll and name it d3dx11_43.it shoul maybe fix it Edit: put it in the bin directory https://user-images.githubusercontent.com/111089725/184501775-90d648ee-e892-40c8-8e3b-2a2423b56ae0.mov

It still doesn't work.

**Comment by MidnightPurple95** [comment]
Same here, tried @TheMispeled method, downloaded, renamed and put in bin, white screen on start-up then crashes.

**Comment by JaoLuca** [comment]
The issue #101 reports the same error and @MrAmos123 solution worked in my case:

Install DirectX https://www.microsoft.com/en-gb/download/details.aspx?id=35

**Comment by Jckf** [comment]
Correct solution has been given, and no reply from ticket author in multiple days. Closing.
