### ISSUE TITLE
How to change parts

### ISSUE THREAD

**Issue by RandomGuyFromAbania** [ange-yaghi/engine-sim#68]
I would like to change some engine parts but i dont know how to do it.

**Comment by Jckf** [comment]
There is no official documentation on how to build or customize an engine, but if you [join our Discord server]([https://discord.gg/chKreEmXw6](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbUZad0JpdW5BZWtBX3dMTUpSV09jbFZ4Vm9yd3xBQ3Jtc0trcWQ5bU9sUmRNdVhwUXNNMGNHdnRMX1NSbnJtVFNoSjc5YTVWd0RyNU9qNW94YTBwRE8xcnotV0tmU0NOWVhnc1AtRE04SjdoZWI2Y1ZReEZ0LVdWRkNEZVJpdG5DODYwTXMxNHcwb0NGalY2c0ZCVQ&q=https%3A%2F%2Fdiscord.gg%2FchKreEmXw6&v=RKT-sKtR970)) and ask there, I bet someone is willing to help you through it :)
