### ISSUE TITLE
Kohler ch750 will start and then on the second frame crash

### ISSUE THREAD

**Issue by Honestlypotato** [ange-yaghi/engine-sim#69]
import "engine_sim.mr"
import "part-library/part_library.mr"
import "engines/bmw/M52B28.mr"
import "engines/chevrolet/chev_truck_454.mr"
import "engines/audi/i5.mr"
import "engines/kohler/kohler_ch750.mr"

set_engine(
    engine: kohler_ch750()
)
is what I put into main.mr but every time I go launch it, it will run for like 5 or 10 frame and then crash. Please help.

**Comment by 14rss** [comment]
Please see #58
The issue is mislabeled audio file directories. That issue will hold your answer (✿╹◡╹)

**Comment by ange-yaghi** [comment]
This was a mistake in my last commit, it'll be corrected in the next version

**Comment by ange-yaghi** [comment]
Issue has been fixed.
