### ISSUE TITLE
Video tutorial how to build

### ISSUE THREAD

**Issue by KILLERMANTV** [ange-yaghi/engine-sim#70]

**Comment by oohwooh** [comment]
I dont see why this would be necessary there are build instructions in the README

**Comment by johnbabiak** [comment]
I would also appreciate a video because I did all the steps and still ran into errors...

**Comment by Welliedowner** [comment]
> I dont see why this would be necessary there are build instructions in the README

Yes, for really techy programming people, the instructions make perfect sense, but I saw the youtube video and i just wanna play around with the engine. But i have no idea what he means by

 "You will need to install the following dependencies and CMake will need to be able to locate them (ie. they need to be listed on your PATH):" 


like what dependiencies, where do we find these dependencies, and what is "my path"

if someone went through step by step that would be great.

**Comment by aniketnegi** [comment]
If you're just interested in trying it out, then there are already instructions on how to download a ready-to-use version of the program in the readme: https://github.com/ange-yaghi/engine-sim#how-do-i-install-it.

**Comment by StanTheAwesomeMan** [comment]
I already made a step by step tutorial [here](https://github.com/StanTheAwesomeMan/engine-sim-build-tutorial)

**Comment by KILLERMANTV** [comment]
> I dont see why this would be necessary there are build instructions in the README

Why bother replying when its useless

> I already made a step by step tutorial [here](https://github.com/StanTheAwesomeMan/engine-sim-build-tutorial)

Thanks bro i exactly needed this

**Comment by Asher-MS** [comment]
> I already made a step by step tutorial [here](https://github.com/StanTheAwesomeMan/engine-sim-build-tutorial)

This is not working now 


`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libboost_filesystem-vc142-mt-x64-1_80.lib'	engine-sim-app	E:\Engine Simulator\engine-sim\build\LINK	1	
`
