### ISSUE TITLE
how to change engine 

### ISSUE THREAD

**Issue by BaguettenButter** [ange-yaghi/engine-sim#75]

**Comment by MilkyDoritos** [comment]
https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions

**Comment by NotoriusNeo** [comment]
If the page doesn't explain it clearly enough:
Inside assets\engines, there are 4 makes (audi, bmw, chevrolet, kohler) pick one. 
Let's say you want to check bmw, open that folder and you'll see a file called M52B28.mr.
Open it using notepad or any other similar software.
Inside M52B28.mr, search for `name`, when you locate the line that says `"name: "BMW M52B28","` look to the previous lines untill you find `public node M52B28`. M52B28 is the reference you have to input on the main.mr file inside the assets folder.
Then, you just have to change the text inside to match the engine you picked.
Your main file now should look like this:
```

import "engine_sim.mr"
import "engines/bmw/M52B28.mr"

set_engine(
    engine: M52B28()
)
```

Cheers!
