### ISSUE TITLE
all releases won't start

### ISSUE THREAD

**Issue by xandersalarie** [ange-yaghi/engine-sim#76]
when i start the program it auto closes itself again right away, i get as far as a 1 to 2 second white screen before it closes.

is there an logfile i (or you) can look at?

**Comment by MilkMan1093** [comment]
I had this problem too. You need to install DirectX. Download it here. https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by GameClash** [comment]
it still wont open
