### ISSUE TITLE
Feature requests: Engine physical/visual temperatures and fine throttle movement instead of quarters

### ISSUE THREAD

**Issue by KassIsLegend** [ange-yaghi/engine-sim#79]
Engine physical temperatures: physically makes the pistons/components glow/begin to glow red hot above a certain temperature

Fine throttle movement: add a hotkey or just outright change the throttle control to the scroll wheel of the mouse for very fine throttle control, and maybe with a toggle sticky option?

**Comment by ange-yaghi** [comment]
Fine throttle control is already supported: just hold space and use the scroll wheel. Engine temperature is a planned addition but is already covered in another issue so I'll mark this as a duplicate.
