### ISSUE TITLE
Piranha not compiling

### ISSUE THREAD

**Issue by DDev247** [ange-yaghi/engine-sim#8]
Hi, So I tried cloning the repo into a folder and then following the instructions but when I try to compile using `cmake --build .` it works but says something like this:
```
D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(242,5): e
rror MSB8066: kompilacja niestandardowa dla elementu "E:\projects\cpp\engine-sim\new\engine-sim\build\CMakeFiles\c13d90
053f35118ca7aaba0ca881c914\parser.auto.cpp.rule;E:\projects\cpp\engine-sim\new\engine-sim\build\CMakeFiles\c13d90053f35
118ca7aaba0ca881c914\scanner.auto.cpp.rule;E:\projects\cpp\engine-sim\new\engine-sim\dependencies\submodules\piranha\CM
akeLists.txt" została zakończona z kodem 63. [E:\projects\cpp\engine-sim\new\engine-sim\build\dependencies\submodules\p
iranha\piranha.vcxproj]
```
Sorry about the error being sort of in polish but it says `custom compilation for element: --- ended with code 63` or something like that.
If someone could help then I would be thankful.

**Comment by DDev247** [comment]
Just saying: I tried everything for like 2 hours today at like midnight so yeah.

**Comment by ange-yaghi** [comment]
There are some other dependencies you'll need for Piranha. If you just want the EXE, there are some available in the releases section

**Comment by DDev247** [comment]
But I have everything installed: Flex, Bison, CMake, and Boost. Cuz everything else compiles.

**Comment by BoogieHasFun** [comment]
> There are some other dependencies you'll need for Piranha. If you just want the EXE, there are some available in the releases section

Please state those dependenices
