### ISSUE TITLE
[feature] Dyno graph scaling with power

### ISSUE THREAD

**Issue by Kevin15673** [ange-yaghi/engine-sim#80]
It'd be nice to have the dyno graph so it scales with power figures, so something with 12hp isn't just a flat line at the bottom while something with 5000hp is off the charts.

**Comment by ange-yaghi** [comment]
I'll add it in v0.1.6a

**Comment by ferdnyc** [comment]
[12hp] ...Lawnmower Simulator? :rofl:

**Comment by Kevin15673** [comment]
> 

It would also be nice for the dyno graph to show numbers indicating the scale and rpm, probably not something you can just do quick a dirty but I'm not sure.

**Comment by ange-yaghi** [comment]
Yeah I do want to add proper scopes with ticks and numbers but it'll take a bit of time. I might add a separate issue for that.

**Comment by ange-yaghi** [comment]
Feature is complete.
