### ISSUE TITLE
Feature Request: Change car weight and gearing

### ISSUE THREAD

**Issue by Kevin15673** [ange-yaghi/engine-sim#85]
It would be nice to have a section in the engine file where you can change the gearing and weight of the simulated car, for lower power (or really high power) engines.

**Comment by ferdnyc** [comment]
Seems to me like you'd need more than just those parameters, then --- to accurately simulate the effects on the engine, you'd also need things like wheel diameter, drivetrain configuration... you'd basically need to simulate the entire _car_, no?

**Comment by Kevin15673** [comment]
> Seems to me like you'd need more than just those parameters, then --- to accurately simulate the effects on the engine, you'd also need things like wheel diameter, drivetrain configuration... you'd basically need to simulate the entire _car_, no?

he already simulates the vehicles air resistance, gearing and weight, I just want the ability to easily change those values since I think they're hard coded.

**Comment by ange-yaghi** [comment]
I just added this in v0.1.9a so I'll close this ticket
