### ISSUE TITLE
[Idea] Discord Rich Presence Support

### ISSUE THREAD

**Issue by 14rss** [ange-yaghi/engine-sim#92]
Just a thought:
[app icon] [version]
[engine name]
[RPM] (or just elapsed time)

I realize that many people don't like rich presences so maybe if this is considered, an option in the config file could disable it.

**Comment by 14rss** [comment]
Mockup:
![image](https://user-images.githubusercontent.com/91225647/184561513-c47a443d-3697-44d3-b246-271b0ddb1a77.png)

**Comment by ange-yaghi** [comment]
Seems like there is some information to do this here: https://discord.com/developers/docs/rich-presence/how-to. I'll look into it when I have time but someone else can also pick this up.

**Comment by AKCore** [comment]
> Seems like there is some information to do this here: https://discord.com/developers/docs/rich-presence/how-to. I'll look into it when I have time but someone else can also pick this up.

Ill add it Ange. I have experience with discord rich presence.

**Comment by Jckf** [comment]
This was added in v0.1.7 afaik. Closing.
