### ISSUE TITLE
The code execution cannot proceed because VCRUNTIME140_1.dll was not found. Reinstalling the program may fix the problem.

### ISSUE THREAD

**Issue by MidnightPurple95** [ange-yaghi/engine-sim#93]
![image](https://user-images.githubusercontent.com/111256440/184561412-206ba70e-c1a3-4aa6-815c-dc420b833a84.png)

Getting this error code when running engine-sim-app.exe from release V0.1.5a.

**Comment by ange-yaghi** [comment]
For now, these DLLs can be found online but the "correct" way to fix this is to install the Visual Studio C runtime: https://aka.ms/vs/17/release/vc_redist.x64.exe.

**Comment by MidnightPurple95** [comment]
Did the install from your link. Also is having message from missing d3dx11_43.dll. Downloaded and put in bin folded the d3dx11_43.dll. Now I'm getting a white screen on start-up then it closes. Any idea?

**Comment by CompaqDisc** [comment]
> Did the install from your link. Also is having message from missing d3dx11_43.dll. Downloaded and put in bin folded the d3dx11_43.dll. Now I'm getting a white screen on start-up then it closes. Any idea?

You need to install DirectX: http://go.microsoft.com/fwlink/p/?LinkId=159853

**Comment by ricardoboss** [comment]
> Did the install from your link. Also is having message from missing d3dx11_43.dll. Downloaded and put in bin folded the d3dx11_43.dll. Now I'm getting a white screen on start-up then it closes. Any idea?

You may be experiencing #27

**Comment by Jckf** [comment]
Issue appears to have been solved. Closing.
